<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.user.edituserinfomore,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);


	if (pageinfo.PageError==1)
	{


	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("<title>消息提示</title>\r\n");
	XYBody.Append("");	XYBody.Append(pageinfo.Meta);	XYBody.Append("\r\n");
	XYBody.Append("<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body style=\"background-color:#f2f2f2\">\r\n");
	XYBody.Append("<div id=\"sysMsgbox\">\r\n");
	XYBody.Append("	<ul>\r\n");
	XYBody.Append("	    <li class=\"msg\">");	XYBody.Append(pageinfo.MsgboxText);	XYBody.Append("</li>\r\n");
	XYBody.Append("        <li><a href=\"");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("\">");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("</a></li>\r\n");
	XYBody.Append("         <li><a href=\"#\" onclick=\"history.back();\">返回继续操作</a></li>\r\n");
	XYBody.Append("        <li><a href=\"/\">返回首页</a> | <a href=\"#\" onclick=\"window.close();\">关闭本页</a></li>\r\n");
	XYBody.Append("    </ul>\r\n");
	XYBody.Append("    <div id=\"r_f\">2000-2009　" +  XYECOMCreateHTML("XY_Copyright").ToString() + "　版权所有　纵横易商软件</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");



	Response.Write(XYBody.ToString());
System.Web.HttpContext.Current.Response.End();
	

	}	//end if

	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("    <title>");	XYBody.Append(userinfo.name.ToString());	XYBody.Append("</title>\r\n");
	XYBody.Append("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
	XYBody.Append("    <meta content=\"个人中心\" name=\"keywords\">\r\n");
	XYBody.Append("    <meta content=\"\" name=\"description\">\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/css/main.css\" rel=\"stylesheet\"\r\n");
	XYBody.Append("        type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"/common/css/XYLib.css\" type=\"text/css\" rel=\"Stylesheet\" />\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("config/js/config.js\"></" + "script>\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\"></" + "script>\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/UploadControl.js\"></" + "script>\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/date.js\"></" + "script>\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/js/common.js\"></" + "script>\r\n");
	XYBody.Append("    <script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/js/validate.js\"></" + "script>\r\n");
	XYBody.Append("    ");	XYBody.Append(pageinfo.Meta);	XYBody.Append("\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body onload=\"");	XYBody.Append(pageinfo.OnLoadEvents);	XYBody.Append("\">\r\n");
	XYBody.Append("    <div class=\"div_body\">\r\n");
	XYBody.Append("        <div class=\"New_top\">\r\n");
	XYBody.Append("            <div class=\"more\">\r\n");
	XYBody.Append("                <ul>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("\">首页</a> </li>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("news/\">行业资讯</a> </li>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("offer/\">产品库</a> </li>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("investment/\">招商加盟</a> </li>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("exhibition/\">展会</a> </li>\r\n");
	XYBody.Append("                    <li><a class=\"zeroc\" href=\"");	XYBody.Append(config.weburl);	XYBody.Append("job/\">人才</a> </li>\r\n");
	XYBody.Append("                </ul>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div class=\"r\">\r\n");
	XYBody.Append("                <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("user/index.");	XYBody.Append(config.suffix);	XYBody.Append("\" style=\"font-weight: bold; text-decoration: underline;\">\r\n");
	XYBody.Append("                    ");	XYBody.Append(userinfo.loginname.ToString());	XYBody.Append("</a> | <a href=\"");	XYBody.Append(userinfo.shopindex.ToString());	XYBody.Append("\" target=\"_blank\">我的商铺</a>\r\n");
	XYBody.Append("                | <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">退出</a> | <a href=\"\">帮助</a>&nbsp;\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"Head\">\r\n");
	XYBody.Append("        <div class=\"Head_1\">\r\n");
	XYBody.Append("            <img src=\"/templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/images/logo.gif\" /></div>\r\n");
	XYBody.Append("        <div class=\"Head_2 mt8\">\r\n");
	XYBody.Append("            ");	XYBody.Append(userinfo.name.ToString());	XYBody.Append("</div>\r\n");
	XYBody.Append("        <div class=\"Head_3\">\r\n");
	XYBody.Append("            <input value=\"\" id=\"txtsearchkey\" /><a href=\"#\" onclick=\"searchClick();\">搜索</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"Head_4\">\r\n");
	XYBody.Append("            <div class=\"index\">\r\n");
	XYBody.Append("                <div class=\"act\" id=\"_m_index\">\r\n");
	XYBody.Append("                    <a href=\"index.");	XYBody.Append(config.suffix);	XYBody.Append("\">主 页</a></div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div onmouseover=\"document.getElementById('frend').style.display='block';\" onmouseout=\"document.getElementById('frend').style.display='none';\">\r\n");
	XYBody.Append("                <div>\r\n");
	XYBody.Append("                    <div class=\"menu\" id=\"frend\" style=\"z-index: 999;\">\r\n");
	XYBody.Append("                        <a href=\"infoselect.");	XYBody.Append(config.suffix);	XYBody.Append("\">发布信息</a> <a href=\"addnews.");	XYBody.Append(config.suffix);	XYBody.Append("\">发布资讯</a>\r\n");
	XYBody.Append("                        <a href=\"engageadd.");	XYBody.Append(config.suffix);	XYBody.Append("\">发布招聘</a> <a href=\"cashacount.");	XYBody.Append(config.suffix);	XYBody.Append("\">账户管理</a>\r\n");
	XYBody.Append("                    </div>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"nor\" id=\"_m_quick\">\r\n");
	XYBody.Append("                    <a class=\"more\" id=\"f_a\" href=\"infoselect.");	XYBody.Append(config.suffix);	XYBody.Append("\">快捷菜单</a></div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div onmouseover=\"document.getElementById('msg').style.display='block';\" onmouseout=\"document.getElementById('msg').style.display='none';\">\r\n");
	XYBody.Append("                <div>\r\n");
	XYBody.Append("                    <div class=\"menu\" id=\"msg\" style=\"z-index: 999\">\r\n");
	XYBody.Append("                        <a href=\"receivemessagelist.");	XYBody.Append(config.suffix);	XYBody.Append("\">收件箱</a> <a href=\"sendmessagelist.");	XYBody.Append(config.suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                            已发送消息</a> <a href=\"postadministratormessage.");	XYBody.Append(config.suffix);	XYBody.Append("\">给管理员留言</a> <a href=\"joinlist.");	XYBody.Append(config.suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                                收加盟信息</a> <a href=\"joinlist.");	XYBody.Append(config.suffix);	XYBody.Append("?type=send\">已发加盟信息</a>\r\n");
	XYBody.Append("                    </div>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"nor\" id=\"_m_msg\">\r\n");
	XYBody.Append("                    <a class=\"more\" id=\"m_a\" href=\"receivemessagelist.");	XYBody.Append(config.suffix);	XYBody.Append("\">短消息(");	XYBody.Append(userinfo.messagecount.ToString());	XYBody.Append(")</a></div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div class=\"nor\" id=\"_m_userinfo\">\r\n");
	XYBody.Append("                <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("user/edituserinfo.");	XYBody.Append(config.suffix);	XYBody.Append("\">企业资料</a></div>\r\n");
	XYBody.Append("            <div class=\"nor\" id=\"_m_safe\">\r\n");
	XYBody.Append("                <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("user/edituserpassword.");	XYBody.Append(config.suffix);	XYBody.Append("\">安全设置</a></div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <script>xy_Sel_CurTopMenu();</" + "script>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"div_body\" style=\"width: 994px\">\r\n");
	XYBody.Append("        <div class=\"body_bg\">\r\n");
	XYBody.Append("            <div>\r\n");
	XYBody.Append("                <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/images/p1.jpg\"></div>\r\n");
	XYBody.Append("            <div class=\"bodyW\">\r\n");


	XYBody.Append("<div class=\"location fia\"><a href=\"index.");	XYBody.Append(config.Suffix);	XYBody.Append("\">商务中心</a> &gt;  <a href=\"/user/edituserinfo.");	XYBody.Append(config.Suffix);	XYBody.Append("\">基本设置</a> &gt;  补充公司资料</div>\r\n");

	XYBody.Append("<!--\r\n");
	XYBody.Append("    添加链接时，请链接一定需写成 ****绝对路径****\r\n");
	XYBody.Append("    -->\r\n");
	XYBody.Append("<div class=\"Al\">\r\n");
	XYBody.Append("    <div class=\"Al_1\">\r\n");
	XYBody.Append("        会员服务列表:</div>\r\n");
	XYBody.Append("    <div class=\"Al_2\">\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_1\" onclick=\"javascript:switchShow('1')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/a9.gif\">\r\n");
	XYBody.Append("                我的商业信息 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: block\" id=\"div_1\">\r\n");
	XYBody.Append("                <a href=\"/user/infoselect.aspx\">发布商业信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/adv_postbuy.aspx\">发布求购信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/supplybuy.aspx\">管理求购信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/SupplyPubList.aspx\">管理供应信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/teambuy/TeamBuyPublishList.aspx\">管理团购信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/ContractSupplyPubList.aspx\">管理合同担保交易</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/Venture/FinancingList.aspx\">管理融资信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/Venture/InvestmentList.aspx\">管理投资信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/ReceiveAddressList.aspx\">收货人信息管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/DepotList.aspx\">库房信息管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/businesslist.aspx?ename=investment\">管理招商代理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/surrogatelist.aspx?ename=service\">管理服务信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/userbrandlist.aspx\">管理品牌信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/SupplyTypeList.aspx\">自定义分类管理</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_2\" onclick=\"javascript:switchShow('2')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/1.gif\">\r\n");
	XYBody.Append("                关键词排名 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_2\">\r\n");
	XYBody.Append("                <a href=\"/user/searchkeyword.aspx\">搜索关键字</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/curranking.aspx\">正在参与的关键字</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/historyranking.aspx\">排名历史记录</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_3\" onclick=\"javascript:switchShow('3')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/5.gif\">\r\n");
	XYBody.Append("                我的商铺设置 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_3\">\r\n");
	XYBody.Append("                <a href=\"/user/selectshoptemp.aspx\">选择商铺模板</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/uploadlogo.aspx\">上传商铺图片</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/UploadVideo.aspx\">上传形象视频</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/SlidesInfoList.aspx\">幻灯片管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/bindingdomain.aspx\">绑定顶级域名</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/userfirendlink.aspx\">友情链接管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/userannounce.aspx\">商铺公告管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/newlist.aspx\">企业资讯管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/engagelist.aspx\">招聘信息管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/certificatelist.aspx\">企业证书管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/partlist.aspx\">企业专栏管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/usertitleinfolist.aspx\">资讯栏目管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/newlist.aspx\">资讯信息管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/SEO.aspx\">网店SEO设置</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_8\" onclick=\"javascript:switchShow('8')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/3.gif\">\r\n");
	XYBody.Append("                我的交易信息 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_8\">\r\n");
	XYBody.Append("                <a href=\"/user/BuyerOrderList.aspx\">采购管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/SellerOrderList.aspx\">销售管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/Contract/ListBuyerContract.aspx\">作为买家的合同</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/Contract/ListSellerContract.aspx\">作为卖家的合同</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/TeamBuy/TeamSellerOrderList.aspx\">卖家的团购订单</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/TeamBuy/TeamBuyerOrderList.aspx\">买家的团购订单</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_4\" onclick=\"javascript:switchShow('4')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/a9.gif\" alt=\"\" />\r\n");
	XYBody.Append("                分类广告位 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_4\">\r\n");
	XYBody.Append("                <a href=\"/user/buyclassads.aspx\">购买分类广告</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/curclassads.aspx\">正在参与的广告</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/hisclassads.aspx\">历史参与的广告</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_5\" onclick=\"javascript:switchShow('5')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/a10.gif\" alt=\"\" />\r\n");
	XYBody.Append("                我的财务信息 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_5\">\r\n");
	XYBody.Append("                <a href=\"/user/cashacount.aspx\">现金消费明细</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/ContractMargin/SupplementConMargin.aspx\">充值合同保证金</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/inputmoney.aspx\">充值明细</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/invoicelist.aspx\">发票列表</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/invoice.aspx\">申请发票</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/remit.aspx\">汇款确认</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/FictitiouConsumptionInfo.aspx\">网站币消费明细</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_9\" onclick=\"javascript:switchShow('9')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/a9.gif\">\r\n");
	XYBody.Append("                礼品兑换 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_9\">\r\n");
	XYBody.Append("                <a href=\"/user/getgift.aspx\">礼品列表</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/mygift.aspx\">我的礼品</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_7\" onclick=\"javascript:switchShow('7')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/buyer.gif\">\r\n");
	XYBody.Append("                我收藏的信息 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_7\">\r\n");
	XYBody.Append("                <a href=\"/user/companys.aspx\">收藏企业管理</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/favoritelist.aspx\">收藏的商业信息</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("        <dl>\r\n");
	XYBody.Append("            <dt><a style=\"padding-right: 10px\" id=\"a_6\" onclick=\"javascript:switchShow('6')\"\r\n");
	XYBody.Append("                href=\"javascript:void(0);\">\r\n");
	XYBody.Append("                <img src=\"/user/image/a6.gif\">\r\n");
	XYBody.Append("                我的账户信息 </a></dt>\r\n");
	XYBody.Append("            <dd style=\"display: none\" id=\"div_6\">\r\n");
	XYBody.Append("                <a href=\"/user/registerinfo.aspx\">查看注册信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/edituserinfo.aspx\">修改注册信息</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/edituserinfomore.aspx\">补充企业资料</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/edituserpassword.aspx\">修改登陆密码</a><br />\r\n");
	XYBody.Append("                <a href=\"/user/editpaypassword.aspx\">修改支付密码</a><br />\r\n");
	XYBody.Append("            </dd>\r\n");
	XYBody.Append("        </dl>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <script type=\"text/javascript\">\r\n");
	XYBody.Append("        xy_Sel_CurLeftMenu();\r\n");
	XYBody.Append("    </" + "script>\r\n");
	XYBody.Append("</div>\r\n");


	XYBody.Append(" <!--右边区域-->\r\n");
	XYBody.Append("<div id=\"right\">\r\n");
	XYBody.Append("   <form method =\"post\">\r\n");
	XYBody.Append("  <table  class=\"contentl\">\r\n");
	XYBody.Append("  <caption>补充公司资料<span>（*为必填项）补充公司资料，将会增加公司资料完成率</span></caption>\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">企业名称：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("     <input   type=\"text\" value=\"");	XYBody.Append(userinfo.unitname.ToString());	XYBody.Append("\" id=\"companyname\" maxlength=\"20\" size=\"55\"  name =\"companyname\"/><br /> <em>填写与工商注册完全一致的全称。<br/>个体经营者填写执照上的姓名，并注明个体经营。如张三(个体经营)。</em></td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">经营模式：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");

	int md__loop__id=0;
	foreach(DataRow md in modelist.Rows)
	{
		md__loop__id++;

	XYBody.Append("        <input  type=\"checkbox\"  value=\"" + md["M_Type"].ToString().Trim() + "\" name =\"modetype\"/>" + md["M_Type"].ToString().Trim() + "\r\n");

	}	//end loop

	XYBody.Append("        <em>最多只能选择两种经营模式</em>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("     <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">注册资本：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("      <select id=\"moneytype\" style=\"width: 97px\" name =\"moneytype\">\r\n");
	XYBody.Append("        <option value =\"人民币\">人民币</option>\r\n");
	XYBody.Append("        </select> <input id=\"money\" type=\"text\"  name =\"money\" maxlength =\"20\" style=\"width: 83px\" value =\"");	XYBody.Append(userinfo.registeredcapital.ToString());	XYBody.Append("\"/> 万</td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">公司成立年份：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("        <input id=\"companynian\" type=\"text\" name =\"companynian\" value =\"");	XYBody.Append(userinfo.regyear.ToString());	XYBody.Append("\" size=\"6\" maxlength=\"4\"/> \r\n");
	XYBody.Append("        <em>成立年份，如:2005 </em></td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("<tr>\r\n");
	XYBody.Append("<th style=\"width:160px\">\r\n");
	XYBody.Append("公司注册地：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("<td>\r\n");
	XYBody.Append("<div id=\"classType\"></div>\r\n");
	XYBody.Append("<input type =\"hidden\" id=\"citytypeid\"  name=\"citytypeid\"/> \r\n");
	XYBody.Append("<input type =\"hidden\" id=\"provinceid\"  name=\"provinceid\" /> \r\n");
	XYBody.Append("<input type =\"hidden\" id=\"areatypeid\"  name=\"areatypeid\" value=\"");	XYBody.Append(userinfo.regareaid.ToString());	XYBody.Append("\" />\r\n");
	XYBody.Append("<script type=\"text/javascript\">\r\n");
	XYBody.Append("var cla = new ClassType(\"cla\",'area','classType','areatypeid');\r\n");
	XYBody.Append("cla.Mode = \"select\";\r\n");
	XYBody.Append("cla.Init();\r\n");
	XYBody.Append("</" + "script>\r\n");
	XYBody.Append("</td>\r\n");
	XYBody.Append("</tr>\r\n");
	XYBody.Append("   <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">主要经营地点：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("     <input  name=\"address\" type=\"text\"  id=\"address\" maxlength=\"100\" size=\"60\"  value =\"");	XYBody.Append(userinfo.manageaddress.ToString());	XYBody.Append("\"/>\r\n");
	XYBody.Append("     <em>请填写业务部门所在营业地</em>\r\n");
	XYBody.Append("     </td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("  <tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">公司人数：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("    <select name=\"employeetotal\" id=\"employeetotal\">\r\n");
	XYBody.Append("        <option value=\"0\">请选择公司人数</option>\r\n");
	XYBody.Append("        <option value=\"50以下\">50以下</option>\r\n");
	XYBody.Append("        <option value=\"50 ~ 100\">50 ~ 100</option>\r\n");
	XYBody.Append("        <option value=\"100 ~ 200\">100 ~ 200</option>\r\n");
	XYBody.Append("        <option value=\"200以上\">200以上</option>\r\n");
	XYBody.Append("    </select></td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("<tr>\r\n");
	XYBody.Append("    <th style=\"width:160px\">主营产品或服务：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td class=\"unline\">\r\n");
	XYBody.Append("     <input  name=\"pt\" type=\"text\"  id=\"pt\" maxlength=\"10\" size=\"18\"  value=\"");	XYBody.Append(pt.ToString());	XYBody.Append("\"/> <input  name=\"pt1\" type=\"text\"  id=\"pt1\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt1.ToString());	XYBody.Append("\"/>  <input  name=\"pt2\" type=\"text\"  id=\"pt2\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt2.ToString());	XYBody.Append("\"/>   <input  name=\"pt3\" type=\"text\"  id=\"pt3\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt3.ToString());	XYBody.Append("\"/><br />\r\n");
	XYBody.Append("      <input  name=\"pt4\" type=\"text\" id=\"pt4\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt4.ToString());	XYBody.Append("\"/> <input  name=\"pt5\" type=\"text\"  id=\"pt5\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt5.ToString());	XYBody.Append("\"/>  <input  name=\"pt6\" type=\"text\"  id=\"pt6\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt6.ToString());	XYBody.Append("\"/>   <input  name=\"pt7\" type=\"text\"  id=\"pt7\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt7.ToString());	XYBody.Append("\"/><br />\r\n");
	XYBody.Append("      <input  name=\"pt8\" type=\"text\"  id=\"pt8\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt8.ToString());	XYBody.Append("\"/> <input  name=\"pt9\" type=\"text\"  id=\"pt9\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt9.ToString());	XYBody.Append("\"/>  <input  name=\"pt10\" type=\"text\"  id=\"pt10\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt10.ToString());	XYBody.Append("\"/>   <input  name=\"pt11\" type=\"text\"  id=\"pt11\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt11.ToString());	XYBody.Append("\"/> <a  href=\"javascript:;\"  onclick =\"getmore();\"><br>更多</a><br />   \r\n");
	XYBody.Append("      <div style=\"display :none;width:100% \" id=\"pmore\"> \r\n");
	XYBody.Append("      <input  name=\"pt12\" type=\"text\" id=\"pt12\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt12.ToString());	XYBody.Append("\"/>\r\n");
	XYBody.Append("      <input  name=\"pt13\" type=\"text\"  id=\"pt13\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt13.ToString());	XYBody.Append("\"/>  \r\n");
	XYBody.Append("      <input  name=\"pt14\" type=\"text\"  id=\"pt14\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt14.ToString());	XYBody.Append("\"/>   \r\n");
	XYBody.Append("      <input  name=\"pt15\" type=\"text\" id=\"pt15\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt15.ToString());	XYBody.Append("\"/><br />\r\n");
	XYBody.Append("      <input  name=\"pt16\" type=\"text\"  id=\"pt16\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt16.ToString());	XYBody.Append("\"/> \r\n");
	XYBody.Append("      <input  name=\"pt17\" type=\"text\"  id=\"pt17\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt17.ToString());	XYBody.Append("\"/>  \r\n");
	XYBody.Append("      <input  name=\"pt18\" type=\"text\"  id=\"pt18\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt18.ToString());	XYBody.Append("\" />   \r\n");
	XYBody.Append("      <input  name=\"pt19\" type=\"text\"  id=\"pt19\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt19.ToString());	XYBody.Append("\"/><br />\r\n");
	XYBody.Append("      <input  name=\"pt20\" type=\"text\"  id=\"pt20\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt20.ToString());	XYBody.Append("\"/> \r\n");
	XYBody.Append("      <input  name=\"pt21\" type=\"text\"  id=\"pt21\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt21.ToString());	XYBody.Append("\"/>  \r\n");
	XYBody.Append("      <input  name=\"pt22\" type=\"text\"  id=\"pt22\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt22.ToString());	XYBody.Append("\"/>   \r\n");
	XYBody.Append("      <input  name=\"pt23\" type=\"text\"  id=\"pt23\" maxlength=\"10\" size=\"18\" value=\"");	XYBody.Append(pt23.ToString());	XYBody.Append("\"/><br />    \r\n");
	XYBody.Append("      </div><br />\r\n");
	XYBody.Append("      <em>(每空限填1种产品名称,建议10字母以下,如；毛绒玩具)</em>\r\n");
	XYBody.Append("    </td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("  <tr>\r\n");
	XYBody.Append("    <th >简介：<em class=\"red\">*</em></th>\r\n");
	XYBody.Append("    <td>\r\n");
	XYBody.Append("        <textarea id=\"lbjianjie\" cols=\"81\" rows=\"9\" name=\"lbjianjie\">");	XYBody.Append(userinfo.synopsis.ToString());	XYBody.Append("</textarea>\r\n");
	XYBody.Append("        <br />· 请用中文详细说明贵公司的成立的历史,主营产品, 品牌,服务等优势。\r\n");
	XYBody.Append("        <br />· 如果内容过于简单或填写单纯的产品介绍，将有可能无法通过审核。\r\n");
	XYBody.Append("        <br />· 联系方式（电话，传真，手机，电子邮件等）请在会员资料中填写，此处请勿重复填写。\r\n");
	XYBody.Append("     </td>\r\n");
	XYBody.Append("  </tr>\r\n");
	XYBody.Append("  </table>\r\n");
	XYBody.Append("  <input type =\"hidden\"  id=\"getmode\"/>\r\n");
	XYBody.Append("  <table width=\"100%\">\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div class=\"content_action\">\r\n");
	XYBody.Append("          <input name=\"but01\" type =\"submit\" value=\" 确定\" onclick =\"return personinfo();\" class =\"button\" />\r\n");
	XYBody.Append("            <input name=\"but02\" type=\"button\" value=\"取消\" onclick =\"window.location.href='");	XYBody.Append(config.WebURL);	XYBody.Append("user/index.");	XYBody.Append(config.Suffix);	XYBody.Append("'\"  class =\"button\"/>    \r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("    </tr>\r\n");
	XYBody.Append("  </table>\r\n");
	XYBody.Append("</form>\r\n");
	XYBody.Append("</div> \r\n");

	XYBody.Append("</div>\r\n");
	XYBody.Append("<div>\r\n");
	XYBody.Append("    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/user/images/p2.jpg\"></div>\r\n");
	XYBody.Append("<br style=\"font: 0px/0 arial\" clear=\"all\" />\r\n");
	XYBody.Append("<div class=\"foot\">\r\n");
	XYBody.Append("    针对");	XYBody.Append(config.webname);	XYBody.Append("商务中心您有任何使用问题和建议 您可以 <a href=\"\">联系个人中心管理员</a> 或 <a href=\"\">查看帮助</a>\r\n");
	XYBody.Append("    <br>\r\n");
	XYBody.Append("    <a href=\"http://www.xyecom.com\">XYECOM 简介</a> | <a href=\"\">用户注册</a> | <a class=\"lan12i\"\r\n");
	XYBody.Append("        href=\"\" target=\"_top\">广告服务</a> | <a class=\"lan12i\" href=\"\" target=\"_top\">招聘</a>\r\n");
	XYBody.Append("    | <a class=\"lan12i\" href=\"\" target=\"_top\">站点地图</a> | <a class=\"lan12i\" href=\"\" target=\"_top\">\r\n");
	XYBody.Append("        联系方式</a> | <a class=\"lan12i\" href=\"\" target=\"_top\">欢迎投稿 </a>| <a href=\"\">图库\r\n");
	XYBody.Append("    </a>| <a class=\"lan12i\" href=\"\" target=\"_top\">RSS订阅</a>\r\n");
	XYBody.Append("    <br>\r\n");
	XYBody.Append("    Copyright &copy; 2005 - 2009 XYECOM. All rights reserved. ");	XYBody.Append(config.webname);	XYBody.Append(" 版权所有.\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<br style=\"clear: both\">\r\n");
	XYBody.Append("</div> </div> </body> </html> \r\n");



	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
