<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.offer.sort,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");

	XYBody.Append("    <title> 供求 - xyecom 3.0 首页 </title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=\"gb2312\" />\r\n");
	XYBody.Append("		<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/XYLib.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/channel.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/search.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>	\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/validate.js\" language=\"javascript\"></" + "script>\r\n");


	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");



	XYBody.Append("	<div class=\"search\">\r\n");
	XYBody.Append("		<div class=\"sh_tab\">\r\n");
	XYBody.Append("			<div class=\"order\">\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("keyword/\">订购固定排名</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<ul id=\"_xy_big_menu_box\">\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_index\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("\" class=\"tabactive\"><span>首 页</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_news\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("news/index.aspx\"><span>新闻资讯</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_offer\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("offer/index.aspx\"><span>产品中心</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_investment\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("investment/index.aspx\"><span>招商加盟</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_company\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("company/index.aspx\"><span>行业公司</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_job\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("job/index.aspx\"><span>人才招聘</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_brand\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("brand/index.aspx\"><span>行业品牌</span></a></li>				\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_exhibition\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("exhibition/index.aspx\"><span>展会信息</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_survey\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("survey/index.aspx\"><span>调查问卷</span></a></li>\r\n");
	XYBody.Append("				<li style=\"display:none;\"><a href=\"#\"><span>社区交流</span></a></li>\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</ul>\r\n");
	XYBody.Append("			<script type=\"text/javascript\">xy_Sel_CurBigMenu();</" + "script>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"sh_cnt\">\r\n");
	XYBody.Append("			<div id=\"main\">\r\n");
	XYBody.Append("				<input type=\"text\" id=\"txtsearchkey\" name=\"sch_text\" class=\"textsearch\" onkeydown=\"_xy_KeyPress('DoSearch');\"/>\r\n");
	XYBody.Append("				<div class=\"soSelect\" onclick=\"xy_ShowSearchMenu();\">\r\n");
	XYBody.Append("					<div class=\"option_current\" id=\"headSlected\" >产品</div>\r\n");
	XYBody.Append("					<div class=\"option_arrow\">\r\n");
	XYBody.Append("						<a href=\"#\"><span class=\"arrow\"></span></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("					<ul onmouseover=\"drop_mouseover('head')\" onmouseout=\"drop_mouseout('head');\" style=\"display: none;\" class=\"options\" id=\"headSel\">\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('产品','offer','sell');\">产品</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('求购','buy','buy');\">求购</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('招商','investment','sell');\">招商</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('加盟','investment','buy');\">加盟</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('融资','venture','sell');\">融资</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('服务','service','sell');\">服务</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('企业','company','sell');\">企业</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('资讯','news','');\">资讯</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('人才','job','');\">人才</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('品牌','brand','');\">品牌</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('展会','exhibition','');\">展会</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_FlagName\" value=\"offer\"/>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_InfoType\" value=\"sell\"/>\r\n");
	XYBody.Append("				<button value=\"搜索\" id=\"DoSearch\" name=\"DoSearch\" class=\"btsearch\" onclick=\"xy_search();\"/>搜索</button>\r\n");
	XYBody.Append("				<a href=\"/search/advanced_search.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[高级搜索]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("contributor.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[投稿]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("post.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[发布信息]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("baike/index.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[百科]</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"sch_bnr\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_5.jpg\" width=\"170\" height=\"77\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("			<div id=\"hot_schs\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("					<li><strong>热门搜索词：</strong></li>\r\n");
	XYBody.Append("					<li>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReMenSouSuoGuanjianzi").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</li>\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");


	XYBody.Append("	<div id=\"search_nav\">\r\n");
	XYBody.Append("		<strong>您现在的位置：</strong> <a href=\"\" class=\"blue\">网站首页</a> &raquo; <a href=\"\" class=\"blue\">产品列表</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"search_main\">\r\n");
	XYBody.Append("		<div id=\"left\">\r\n");
	XYBody.Append("			<div class=\"sch_cates\">\r\n");
	XYBody.Append("				<h2><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/bg_invest_tit.gif\" width=\"12\" height=\"12\" alt=\"\" align=\"absmiddle\" /> 类目选择：</h2>\r\n");
	XYBody.Append("				<div class=\"sch_cnts\">\r\n");
	XYBody.Append("					<a href=\"##\">益智玩具(7)</a>\r\n");
	XYBody.Append("					<a href=\"##\">电动玩具(2)</a>\r\n");
	XYBody.Append("					<a href=\"##\">传统玩具(2)</a>\r\n");
	XYBody.Append("					<a href=\"##\">模型玩具(2)</a>\r\n");
	XYBody.Append("					<a href=\"##\">传统玩具(2)</a>\r\n");
	XYBody.Append("					<a href=\"##\">模型玩具(2)</a>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"FilterDiv\">\r\n");
	XYBody.Append("				<div id=\"FilterDivA\">\r\n");
	XYBody.Append("					<form name=\"Filter\" method=\"get\" action=\"/search.html\">\r\n");
	XYBody.Append("					<span>每页显示数量:\r\n");
	XYBody.Append("					<select name=\"pageNum\" id=\"pageNum\" onchange=\"SelectItem()\">\r\n");
	XYBody.Append("					<option value=\"10\" >10</option>\r\n");
	XYBody.Append("					<option value=\"20\" selected=\"selected\">20</option>\r\n");
	XYBody.Append("					<option value=\"30\" >30</option>\r\n");
	XYBody.Append("					<option value=\"50\" >50</option>\r\n");
	XYBody.Append("					</select>\r\n");
	XYBody.Append("					<img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/Page_PreNo.gif\" border=\"0\"> <a href=\"/buyer/list/296-p2.html\" title=\"下一页\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/Page_Nextyes.gif\" border=\"0\" /></a></span>\r\n");
	XYBody.Append("					<strong class=\"Font14 redLink\">缩小范围:</strong>\r\n");
	XYBody.Append("					<script language=\"JavaScript\" src=\"/js/Area.js\" type=\"text/javascript\"></" + "script>\r\n");
	XYBody.Append("					<select name=\"Province\" onChange=\"ChangeChild(value, ArrayCatalog1, 'City');\">\r\n");
	XYBody.Append("					<option value=\"\">选择省份</option>\r\n");
	XYBody.Append("					</select>\r\n");
	XYBody.Append("					<select name=\"City\"></select>\r\n");
	XYBody.Append("					<script language=\"javascript\">Init(ArrayCatalog1, 'Province', 'City');</" + "script>\r\n");
	XYBody.Append("					<select name=\"postTime\" id=\"postTime\">\r\n");
	XYBody.Append("					<option value=\"0\">选择产品发布时间范围</option>\r\n");
	XYBody.Append("					<option value=\"1\">显示今日最新</option>\r\n");
	XYBody.Append("					<option value=\"3\">显示最近3天</option>\r\n");
	XYBody.Append("					<option value=\"5\">显示最近5天</option>\r\n");
	XYBody.Append("					<option value=\"7\">显示最近7天</option>\r\n");
	XYBody.Append("					<option value=\"15\">显示最近15天</option>\r\n");
	XYBody.Append("					<option value=\"30\">显示最近30天</option>\r\n");
	XYBody.Append("					<option value=\"60\">显示最近60天</option>\r\n");
	XYBody.Append("					<option value=\"180\">显示最近半年</option>\r\n");
	XYBody.Append("					<option value=\"36500\" >显示所有产品</option>\r\n");
	XYBody.Append("					</select>\r\n");
	XYBody.Append("					<input type=\"submit\" name=\"Submit\" value=\"筛选\" onclick=\"SelectItem()\" />\r\n");
	XYBody.Append("					<input name=\"SmallClassID\" type=\"hidden\" id=\"SmallClassID\" value=\"296\" />\r\n");
	XYBody.Append("					</form>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"FilterDivB\">\r\n");
	XYBody.Append("					<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
	XYBody.Append("						<tr>\r\n");
	XYBody.Append("							<td width=\"4%\" style=\"padding-left:4px;\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_than.gif\" width=\"13\" height=\"13\" /></td>\r\n");
	XYBody.Append("							<td width=\"14%\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquire.gif\" width=\"79\" height=\"22\" style=\"cursor:pointer;\" onclick=\"inquire()\" /></td>\r\n");
	XYBody.Append("							<td width=\"51%\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_Order_icon.gif\" width=\"9\" height=\"12\" style=\"position:relative;top:1px;\" /> <a href=\"/buyer/list/296.html\">默认排序</a>&nbsp; <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_Order_icon.gif\" width=\"9\" height=\"12\" style=\"position:relative;top:1px;\" /> <a href=\"/buyer/list/layer/296.html\">按会员级别</a>&nbsp; <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_Order_icon.gif\" width=\"9\" height=\"12\" style=\"position:relative;top:1px;\" /> <a href=\"/buyer/list/date/296.html\">按发布时间</a>&nbsp; <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_Order_icon.gif\" width=\"9\" height=\"12\" style=\"position:relative;top:1px;\" /> <a href=\"/buyer/list/hits/296.html\">按活跃数</a></td>\r\n");
	XYBody.Append("							<td width=\"31%\" align=\"right\"><a href=\"#\" class=\"orange\" target=\"_blank\">| 申请固定排名,让您的产品排在前三位</a></td>\r\n");
	XYBody.Append("						</tr>\r\n");
	XYBody.Append("					</table>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"FixName\"></div>\r\n");
	XYBody.Append("			<div id=\"FixText\">\r\n");
	XYBody.Append("				<!-- 以下为程序提取静态块 -->\r\n");
	XYBody.Append("				<div class=\"ProList\">\r\n");
	XYBody.Append("					<div class=\"ProCheckBox\">\r\n");
	XYBody.Append("						<input name=\"ProID\" type=\"checkbox\" value=\"203379\" />\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"ProPhoto\">\r\n");
	XYBody.Append("						<div class=\"ProPhotoBG_108\"><a href=\"/detail/203379.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic15.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("						<div class=\"ProResults\">[<a href=\"/search.html?UserID=fzhsj\" target=\"_blank\">共有156个相关产品</a>]</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"ProInfo\">\r\n");
	XYBody.Append("						<strong><a href=\"/detail/203379.html\" class=\"ProInfoTitleA\" target=\"_blank\">好施洗洁巾</a></strong><br />…<br />\r\n");
	XYBody.Append("						<a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>福州杰仕日用品有限公司</strong></a> [福建&nbsp;福州]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("						<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁巾</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=洗碗布\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗布</a>]\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"ProContact\">\r\n");
	XYBody.Append("						<br />\r\n");
	XYBody.Append("						<a href=\"/send/203379/fzhsj.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("						<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=281044974&amp;Site=福州杰仕日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("						<a href=\"http://amos1.taobao.com/msg.ww?v=2&amp;uid=蒋宜钗&amp;s=2\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/alitalk.gif\" alt=\"阿里旺旺交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<!-- 以上为程序提取静态块 -->\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"205890\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/205890.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic16.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=baozi\" target=\"_blank\">共有67个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/205890.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁巾</a></strong><br />\r\n");
	XYBody.Append("我公司专业生产各种系列清洁布,清洁用品,纹胸护理袋,欢迎前来定购\r\n");
	XYBody.Append("…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>邵武市宝姿日用品制造有限公司</strong></a> [福建&nbsp;南平]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=清洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">清洁巾</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/205890/baozi.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=783632611&amp;Site=邵武市宝姿日用品制造有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<!--普通列表-->\r\n");
	XYBody.Append("	<div id=\"ProDiv\">\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"204869\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/204869.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic17.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=chinayajie\" target=\"_blank\">共有137个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/204869.html\" class=\"ProInfoTitleA\" target=\"_blank\">提花擦洗块YJ-8015</a></strong><br />\r\n");
	XYBody.Append("我公司是一家专业生产新一代高品质的厨房清洁用品原料及成品；刷洗大王，百洁布，擦洗块,洗碗布,揩布,洗洁布,海绵擦洗块，金…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>东阳市雅洁卫生保健品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=洗碗布\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗布</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=擦洗块\" target=\"_blank\" class=\"ProInfoKeyA\">擦洗块</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/204869/chinayajie.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=188958622&amp;Site=东阳市雅洁卫生保健品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"207137\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/207137.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic18.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=dannijia\" target=\"_blank\">共有212个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/207137.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁巾</a></strong><br />\r\n");
	XYBody.Append("公司产品主要有刷洗大王系列、百洁布、洗碗布、清洁球、海绵制品、沐浴花、浴帽、围裙等。…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>金华市丹妮日用品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=揩布\" target=\"_blank\" class=\"ProInfoKeyA\">揩布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/207137/dannijia.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=244043699&amp;Site=金华市丹妮日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"206566\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/206566.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic15.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=fenfang\" target=\"_blank\">共有134个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/206566.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗碗巾</a></strong><br />\r\n");
	XYBody.Append(" …<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>瑞安市芬芳日用品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗碗巾\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗巾</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=清洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">清洁巾</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/206566/fenfang.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=120332995&amp;Site=瑞安市芬芳日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"226688\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG\"><a href=\"/detail/226688.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic16.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/226688.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁布</a></strong><br />\r\n");
	XYBody.Append("本厂主要生产各类毛巾,清洁巾,浴裙,宠物巾,汽车美容巾等产品.…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>义乌市通海经编有限公司</strong></a> [浙江&nbsp;义乌市]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=揩布\" target=\"_blank\" class=\"ProInfoKeyA\">揩布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/226688/tonghai.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=1093708331\"584631591&amp;Site=义乌市通海经编有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"msnim:chat?contact=thjbdonna19870126@hotmail.com\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/msn.gif\" alt=\"MSN交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"209858\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/209858.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic17.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=sunday\" target=\"_blank\">共有82个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/209858.html\" class=\"ProInfoTitleA\" target=\"_blank\">新迪日用品</a></strong><br />\r\n");
	XYBody.Append("能有效清洁…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>义乌市盈福百洁布厂</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=百货\" target=\"_blank\" class=\"ProInfoKeyA\">百货</a>, <a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/209858/sunday.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=574974603,8692800&amp;Site=义乌市盈福百洁布厂&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"msnim:chat?contact=sunday1945@hotmail.com\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/msn.gif\" alt=\"MSN交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"http://amos1.taobao.com/msg.ww?v=2&amp;uid=JUDEE&amp;s=2\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/alitalk.gif\" alt=\"阿里旺旺交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"211844\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/211844.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic18.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=oulejie\" target=\"_blank\">共有128个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/211844.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁布</a></strong><br />\r\n");
	XYBody.Append("  …<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>揭西县欧乐洁日用品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"http://oulejie.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=洗碗布\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/211844/oulejie.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=443252659&amp;Site=揭西县欧乐洁日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"http://amos1.taobao.com/msg.ww?v=2&amp;uid=gddjryp&amp;s=2\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/alitalk.gif\" alt=\"阿里旺旺交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"123475\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/123475.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic16.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=ofcourse\" target=\"_blank\">共有133个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/123475.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁布</a></strong><br />\r\n");
	XYBody.Append("…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>东阳市欧科仕家居日用品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"http://ofcourse.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗碗布\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗布</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/123475/ofcourse.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=345935235&amp;Site=东阳市欧科仕家居日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"msnim:chat?contact=dysponge@hotmail.com\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/msn.gif\" alt=\"MSN交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"205891\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/205891.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic17.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=baozi\" target=\"_blank\">共有67个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/205891.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁巾</a></strong><br />\r\n");
	XYBody.Append("我公司专业生产各种系列清洁布,清洁用品,纹胸护理袋,欢迎前来定购\r\n");
	XYBody.Append("…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>邵武市宝姿日用品制造有限公司</strong></a> [福建&nbsp;南平]&nbsp;&nbsp;<a href=\"http://baozi.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"http://www.ryp.cn/about/JPmember.htm\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=清洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">清洁巾</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/205891/baozi.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=783632611&amp;Site=邵武市宝姿日用品制造有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"205939\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/205939.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic18.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=cnsanqing\" target=\"_blank\">共有271个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/205939.html\" class=\"ProInfoTitleA\" target=\"_blank\">三清超细纤维清洁巾</a></strong><br />\r\n");
	XYBody.Append(" 规格：40cm×40cm\r\n");
	XYBody.Append(" 数量：60包/箱…<br />\r\n");
	XYBody.Append("		  <a href=\"\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>福建省邵武市三清日用品有限公司</strong></a> [福建&nbsp;南平]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"http://www.ryp.cn/about/JPmember.htm\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=揩布\" target=\"_blank\" class=\"ProInfoKeyA\">揩布</a>, <a href=\"/search.html?keyword=清洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">清洁巾</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/205939/cnsanqing.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=782263539&amp;Site=福建省邵武市三清日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"157257\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/157257.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic15.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=ywltt\" target=\"_blank\">共有259个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/157257.html\" class=\"ProInfoTitleA\" target=\"_blank\">天使漫舞抹布</a></strong><br />\r\n");
	XYBody.Append("…<br />\r\n");
	XYBody.Append("		  <a href=\"\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>义乌市乐淘淘日用品批发网</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"http://ywltt.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"http://www.ryp.cn/about/JPmember.htm\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=清洁布\" target=\"_blank\" class=\"ProInfoKeyA\">清洁布</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/157257/ywltt.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=458310146&amp;Site=义乌市乐淘淘日用品批发网&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"203505\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/203505.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic16.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=fzhsj\" target=\"_blank\">共有156个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/203505.html\" class=\"ProInfoTitleA\" target=\"_blank\">好杰仕洗洁布 </a></strong><br />\r\n");
	XYBody.Append("…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>福州杰仕日用品有限公司</strong></a> [福建&nbsp;福州]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁巾</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=洗碗布\" target=\"_blank\" class=\"ProInfoKeyA\">洗碗布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/203505/fzhsj.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=281044974&amp;Site=福州杰仕日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"http://amos1.taobao.com/msg.ww?v=2&amp;uid=蒋宜钗&amp;s=2\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/alitalk.gif\" alt=\"阿里旺旺交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"97779\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/97779.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic17.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=Hongliang\" target=\"_blank\">共有45个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/97779.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁布</a></strong><br />\r\n");
	XYBody.Append("供应清洁用品…<br />\r\n");
	XYBody.Append("		  <a href=\"http://Hongliang.ryp.cn\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>东阳市洪良日用品有限公司</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"http://Hongliang.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=擦布\" target=\"_blank\" class=\"ProInfoKeyA\">擦布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/97779/Hongliang.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=549718696&amp;Site=东阳市洪良日用品有限公司&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"200589\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/200589.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic15.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=jintu\" target=\"_blank\">共有118个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/200589.html\" class=\"ProInfoTitleA\" target=\"_blank\">洗洁巾</a></strong><br />\r\n");
	XYBody.Append("    …<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>金华市金兔日用工艺品厂</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=洗洁巾\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁巾</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>, <a href=\"/search.html?keyword=揩布\" target=\"_blank\" class=\"ProInfoKeyA\">揩布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/200589/jintu.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"http://wpa.qq.com/msgrd?V=1&amp;Uin=405822749&amp;Site=金华市金兔日用工艺品厂&amp;Menu=yes\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/QQ.gif\" alt=\"QQ交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("<a href=\"Skype:wujingtu35207?call\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/Skype.gif\" alt=\"Skype交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"204823\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/204823.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic18.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=ywyuhui\" target=\"_blank\">共有33个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/204823.html\" class=\"ProInfoTitleA\" target=\"_blank\">清洁布</a></strong><br />\r\n");
	XYBody.Append(" 浙江煜辉日用品有限公司位于义乌市江东街道（青口）东苑工业园区，主要生产以下系列产品：PP、PVC餐垫、台垫、PEVA、…<br />\r\n");
	XYBody.Append("		  <a href=\"http://ywyuhui.ryp.cn\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>义乌煜辉日用品厂</strong></a> [浙江&nbsp;金华]&nbsp;&nbsp;<a href=\"http://ywyuhui.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=抹布\" target=\"_blank\" class=\"ProInfoKeyA\">抹布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/204823/ywyuhui.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	      <div class=\"ProList\">\r\n");
	XYBody.Append("        <div class=\"ProCheckBox\"><input name=\"ProID\" type=\"checkbox\" value=\"205366\" />\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"ProPhoto\">\r\n");
	XYBody.Append("			<div class=\"ProPhotoBG_108\"><a href=\"/detail/205366.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp/pic17.jpg\" alt=\"\" border=\"0\" onload=\"LoadImg(100,100,this)\" /></a></div>\r\n");
	XYBody.Append("			<div class=\"ProResults\">[<a href=\"/search.html?UserID=lefu\" target=\"_blank\">共有22个相关产品</a>]</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("        <div class=\"ProInfo\">\r\n");
	XYBody.Append("			<strong><a href=\"/detail/205366.html\" class=\"ProInfoTitleA\" target=\"_blank\">抹布</a></strong><br />\r\n");
	XYBody.Append("企业由针织制衣厂、无纺布及无纺布制品厂、高科技无纺材料公司等组成，素以“产品科技含量高、生产加工精”见长。同时不断努力开…<br />\r\n");
	XYBody.Append("		  <a href=\"#\" target=\"_blank\" class=\"ProInfoKeyA\"><strong>浙江乐芙技术纺织品有限公司</strong></a> [浙江&nbsp;绍兴]&nbsp;&nbsp;<a href=\"http://lefu.ryp.cn/contactus.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/contactIcon.gif\" alt=\"查看联系方式\" width=\"69\" height=\"21\" border=\"0\" style=\"vertical-align:middle\" /></a><br />\r\n");
	XYBody.Append("          <a href=\"#\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/goldIcon.gif\" border=\"0\" style=\"position:relative;top:5px;\" /></a> [关键词：<a href=\"/search.html?keyword=清洁用品\" target=\"_blank\" class=\"ProInfoKeyA\">清洁用品</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=揩布\" target=\"_blank\" class=\"ProInfoKeyA\">揩布</a>, <a href=\"/search.html?keyword=洗洁布\" target=\"_blank\" class=\"ProInfoKeyA\">洗洁布</a>, <a href=\"/search.html?keyword=擦洗布\" target=\"_blank\" class=\"ProInfoKeyA\">擦洗布</a>]</div>\r\n");
	XYBody.Append("        <div class=\"ProContact\"><br />\r\n");
	XYBody.Append("          <a href=\"/send/205366/lefu.html\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquireIcon.gif\" width=\"69\" height=\"21\" border=\"0\" /></a><br />\r\n");
	XYBody.Append("<a href=\"msnim:chat?contact=vinaxu@msn.com\" target=\"_blank\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/msn.gif\" alt=\"MSN交谈\" border=\"0\" /></a>\r\n");
	XYBody.Append("		  </div>\r\n");
	XYBody.Append("<div style=\"clear:left;\" class=\"ProLine\"></div>\r\n");
	XYBody.Append("      </div>\r\n");
	XYBody.Append("	  </div>\r\n");
	XYBody.Append("<!--普通列表结束-->\r\n");
	XYBody.Append("	<div id=\"ProFind\"><strong class=\"orange\">还没有找到合适的产品?</strong>  赶快<a href=\"#\" target=\"_blank\">发布求购信息</a>，让供应商主动来找您！</div>\r\n");
	XYBody.Append("	<div id=\"ProThan\">\r\n");
	XYBody.Append("	  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("          <td width=\"4%\" style=\"padding-left:4px;\"><span style=\"padding-left:4px;\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_than.gif\" width=\"13\" height=\"13\" /></span></td>\r\n");
	XYBody.Append("          <td width=\"12%\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/inquire.gif\" width=\"79\" height=\"22\" style=\"cursor:pointer;\" onclick=\"inquire()\" /></td>\r\n");
	XYBody.Append("          <td width=\"3%\">或</td>\r\n");
	XYBody.Append("          <td width=\"57%\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/than.gif\" width=\"79\" height=\"22\"  style=\"cursor:pointer;\" onclick=\"thanpro()\" /></td>\r\n");
	XYBody.Append("          <td width=\"24%\" align=\"right\"><a href=\"/buyer/7.html\">↑返回到清洁用品行业</a></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("      </table>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	</form>\r\n");
	XYBody.Append("		<div id=\"splitPage\"><form method=\"get\" onsubmit=\"document.location = '/buyer/list/296-p'+this.page.value+'.html';return false;\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_previous.gif\" border=\"0\" style=\"position:relative;top:5px;\">&nbsp;<a href=\"/buyer/list/296-p1.html\" class=\"thispage\">1</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p2.html\">2</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p3.html\">3</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p4.html\">4</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p5.html\">5</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p6.html\">6</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p7.html\">7</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p8.html\">8</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p9.html\">9</a><span style=\"color:#D7D7D7\">|</span> <a href=\"/buyer/list/296-p10.html\">10</a>&nbsp;&nbsp;<a href=\"/buyer/list/296-p2.html\" title=\"下一页\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/list_next.gif\" border=\"0\" style=\"position:relative;top:5px;\"></a>&nbsp;&nbsp;&nbsp;<span style=\"font-size:14px;\">直接转到</span>&nbsp;<input name=\"pageformat\" type=\"hidden\" value=\".html\"><input name=page size=3 style=\"height:13px;\" value=1>&nbsp;<span style=\"font-size:14px;\">页</span>&nbsp;<input type=submit value=\"确定>>\" style=\"height:20px;\"><br><br><span style=\"font-size:14px;\">共 <strong class=\"orange\">490</strong> 条记录&nbsp;&nbsp;&nbsp;当前为第 <strong class=\"orange\">1</strong> 页&nbsp;&nbsp;&nbsp;共 <strong class=\"orange\">25</strong> 页&nbsp;&nbsp;&nbsp;<strong class=\"orange\">20</strong> 条/页</span></form></div>\r\n");
	XYBody.Append("	<!-- 左侧结束 -->\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<center><a target=\"_blank\" href=\"#\" class=\"red big\"><strong>黄金展位</strong></a></center>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"Mblk_01\">\r\n");
	XYBody.Append("				<br />\r\n");
	XYBody.Append("				<div class=\"news_exhi\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_11.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("						<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_22.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("						<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_33.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>怎样推广我的产品？</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">多国暴发甲型H1N1流感</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">胡锦涛出席上合峰会</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">伊朗大选引发政局动荡</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">成都公交车发生燃烧</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">法航空客A330客机坠毁</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">成都公交车发生燃烧</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">法航空客A330客机坠毁</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>展会技巧</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">多国暴发甲型H1N1流感</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">胡锦涛出席上合峰会</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">伊朗大选引发政局动荡</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">成都公交车发生燃烧</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">法航空客A330客机坠毁</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">成都公交车发生燃烧</a></li>\r\n");
	XYBody.Append("						<li><a target=\"_blank\" href=\"#\">法航空客A330客机坠毁</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
