<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.area.index,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("    <title>");	XYBody.Append(seo.Title);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"");	XYBody.Append(seo.Description);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"");	XYBody.Append(seo.Keywords);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=\"gb2312\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/channel.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/news.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>	\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");



	XYBody.Append("	<div class=\"search\">\r\n");
	XYBody.Append("		<div class=\"sh_tab\">\r\n");
	XYBody.Append("			<div class=\"order\">\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("keyword/\">订购固定排名</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<ul id=\"_xy_big_menu_box\">\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_index\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("\" class=\"tabactive\"><span>首 页</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_news\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("news/index.aspx\"><span>新闻资讯</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_offer\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("offer/index.aspx\"><span>产品中心</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_investment\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("investment/index.aspx\"><span>招商加盟</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_company\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("company/index.aspx\"><span>行业公司</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_job\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("job/index.aspx\"><span>人才招聘</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_brand\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("brand/index.aspx\"><span>行业品牌</span></a></li>				\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_exhibition\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("exhibition/index.aspx\"><span>展会信息</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_survey\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("survey/index.aspx\"><span>调查问卷</span></a></li>\r\n");
	XYBody.Append("				<li style=\"display:none;\"><a href=\"#\"><span>社区交流</span></a></li>\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</ul>\r\n");
	XYBody.Append("			<script type=\"text/javascript\">xy_Sel_CurBigMenu();</" + "script>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"sh_cnt\">\r\n");
	XYBody.Append("			<div id=\"main\">\r\n");
	XYBody.Append("				<input type=\"text\" id=\"txtsearchkey\" name=\"sch_text\" class=\"textsearch\" onkeydown=\"_xy_KeyPress('DoSearch');\"/>\r\n");
	XYBody.Append("				<div class=\"soSelect\" onclick=\"xy_ShowSearchMenu();\">\r\n");
	XYBody.Append("					<div class=\"option_current\" id=\"headSlected\" >产品</div>\r\n");
	XYBody.Append("					<div class=\"option_arrow\">\r\n");
	XYBody.Append("						<a href=\"#\"><span class=\"arrow\"></span></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("					<ul onmouseover=\"drop_mouseover('head')\" onmouseout=\"drop_mouseout('head');\" style=\"display: none;\" class=\"options\" id=\"headSel\">\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('产品','offer','sell');\">产品</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('求购','buy','buy');\">求购</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('招商','investment','sell');\">招商</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('加盟','investment','buy');\">加盟</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('融资','venture','sell');\">融资</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('服务','service','sell');\">服务</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('企业','company','sell');\">企业</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('资讯','news','');\">资讯</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('人才','job','');\">人才</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('品牌','brand','');\">品牌</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('展会','exhibition','');\">展会</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_FlagName\" value=\"offer\"/>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_InfoType\" value=\"sell\"/>\r\n");
	XYBody.Append("				<button value=\"搜索\" id=\"DoSearch\" name=\"DoSearch\" class=\"btsearch\" onclick=\"xy_search();\"/>搜索</button>\r\n");
	XYBody.Append("				<a href=\"/search/advanced_search.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[高级搜索]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("contributor.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[投稿]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("post.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[发布信息]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("baike/index.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[百科]</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"sch_bnr\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_5.jpg\" width=\"170\" height=\"77\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("			<div id=\"hot_schs\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("					<li><strong>热门搜索词：</strong></li>\r\n");
	XYBody.Append("					<li>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReMenSouSuoGuanjianzi").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</li>\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");





	XYBody.Append("	<div id=\"best_cmpy\">\r\n");
	XYBody.Append("		<ul>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_3.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_4.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_3.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_4.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("		</ul>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"city_cnt\">\r\n");
	XYBody.Append("		<div id=\"lt_cnt\">\r\n");
	XYBody.Append("			<div id=\"left_A\">\r\n");
	XYBody.Append("				<div id=\"news_slide\">\r\n");
	XYBody.Append("				" +  XYECOMCreateHTML("XY_SlideTop5ByNewsIndex").ToString() + "\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"spacer height6\"></div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("					<h2 id=\"h2_1\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>");	XYBody.Append(areaname.ToString());	XYBody.Append("农业资讯</strong></a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"x_box1\" class=\"Mblk_01\" style=\"display:none;\">\r\n");
	XYBody.Append("					<div class=\"pictext\">\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"com_pages\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_AreaZiXunListLeft").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"spacer height6\"></div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h2_2\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>");	XYBody.Append(areaname.ToString());	XYBody.Append("名优企业</strong></a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"y_box1\" class=\"Mblk_01\" style=\"border-bottom:0; display:block;\">\r\n");
	XYBody.Append("					<div class=\"rank_compy\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_MingYouQiYe").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"left_B\">\r\n");
	XYBody.Append("                <!-- 地方站要闻-->\r\n");
	XYBody.Append("				<div id=\"headline\">\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_AreaYaoWenTop").ToString() + "\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"clear\"></div>\r\n");
	XYBody.Append("				<ul class=\"mid_ul\">\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_AreaYaoWenZiXun").ToString() + "\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("				<div class=\"spacer city_rt_spacer6\"></div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("					<h2 id=\"h201\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>推荐信息</strong></a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("					<ul class=\"photo_news\">\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_AreaGongYingXinXiIMG").ToString() + "\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("					<div class=\"com_pages\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_AreaGongYingXinXiFont").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"spacer city_rt_spacer6\"></div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("					<h2 id=\"h201\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>最新供求</strong></a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"con01\" class=\"Mblk_01\" style=\"border-bottom:0;\">\r\n");
	XYBody.Append("					<div class=\"com_pages\" style=\"width:45%;float:left;\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_ZuiXinGongQiu6").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"com_pages\" style=\"width:45%;float:left;\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_ZuiXinQiuGou6").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("			<div class=\"spacer\" id=\"city_spacer_1\"></div>\r\n");
	XYBody.Append("			<div id=\"offers\" style=\"margin:0;\">\r\n");
	XYBody.Append("				<div id=\"tit\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li class=\"current\" onmouseover=\"document.getElementById('remcd_offer').style.display='none';document.getElementById('remcd_supply').style.display='block';document.getElementById('tab_supply').className='current';document.getElementById('tab_offer').className='';\" id=\"tab_supply\">推荐供应</li>\r\n");
	XYBody.Append("						<li onmouseover=\"document.getElementById('remcd_supply').style.display='none';document.getElementById('remcd_offer').style.display='block';document.getElementById('tab_supply').className='';document.getElementById('tab_offer').className='current';\" id=\"tab_offer\">推荐求购</li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"remcd_supply\">\r\n");
	XYBody.Append("					<div id=\"pic_cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_TuiJianGongYingIMG").ToString() + "\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_TuiJianGongYingFont").ToString() + "\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"hasty_offer\">\r\n");
	XYBody.Append("						<div class=\"h_lt\">紧急求购：</div>\r\n");
	XYBody.Append("						<div class=\"h_rt\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_Index_JinJiQiuGou").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"remcd_offer\" style=\"display:none;\">\r\n");
	XYBody.Append("					<div id=\"pic_cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_TuiJianQiuGouIMG").ToString() + "\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_TuiJianQiuGouFont").ToString() + "\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"hasty_offer\">\r\n");
	XYBody.Append("						<div class=\"h_lt\">紧急求购：</div>\r\n");
	XYBody.Append("						<div class=\"h_rt\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_Index_JinJiQiuGou").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer\" id=\"city_spacer_2\"></div>\r\n");
	XYBody.Append("			<div class=\"area1\" style=\"background:white;border-bottom:0;\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_news\"><h2>热点资讯</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"info_lt\">\r\n");
	XYBody.Append("						<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_8.jpg\" width=\"220\" height=\"110\" alt=\"\" /></a>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReDianZiXunLeft").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"info_rt\">\r\n");
	XYBody.Append("						<div class=\"Bm_1\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReDianZiXunRight").ToString() + "\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"Bm_11\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReDianZiXuntop1").ToString() + "\r\n");
	XYBody.Append("							<ul class=\"Bm_12 fia\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReDianZiXuncenter").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("            <div class=\"spacer\" id=\"city_spacer_2\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"rt_cnt\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>");	XYBody.Append(areaname.ToString());	XYBody.Append("简介</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"commonBoxCont\">\r\n");
	XYBody.Append("					<div class=\"siteRecommendImg\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/hangzhou.gif\" alt=\"杭州介绍\" /></div>\r\n");
	XYBody.Append("					<div class=\"siteRecommendDetail\">\r\n");
	XYBody.Append("						<p>\r\n");
	XYBody.Append("							长江三角洲重要中心城市和中国东南部交通枢纽。 自秦时设县治以来，已有2200多年历史。早在5500年前，就有人类在此繁衍生息，并产生了被称为文明曙光的良渚文化。杭州是我国的七大古都之一。\r\n");
	XYBody.Append("						</p>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer city_rt_spacer6\"></div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>");	XYBody.Append(areaname.ToString());	XYBody.Append("农产品：</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\" style=\"width:221px;overflow:hidden;\">\r\n");
	XYBody.Append("				<div class=\"cnt\" id=\"price\">\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer city_rt_spacer6\"></div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>");	XYBody.Append(areaname.ToString());	XYBody.Append("动态</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\" style=\"border-bottom:0;\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_WangZhanDongTai").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("		<div class=\"spacer\" id=\"city_spacer_3\"></div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div class=\"hy_brand clr\">\r\n");
	XYBody.Append("		<div class=\"tit\">行业推荐品牌</div>\r\n");
	XYBody.Append("		<div class=\"brand_pic\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				" +  XYECOMCreateHTML("XY_Index_HangYePinPai").ToString() + "\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</ul>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
