//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CompanyProductTypeInfo.autogenerated.cs
// author: wangzhen
// create date：2011-3-29 16:18:42
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
	public partial class CompanyProductTypeInfo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private int _id;
		
		/// <summary>
		/// 
		/// </summary>
		private string _ptName;
		
		/// <summary>
		/// 
		/// </summary>
		private int _infoCount;
		
		/// <summary>
		/// 
		/// </summary>
		private long _userId;
		
		/// <summary>
		/// 
		/// </summary>
		private long _parentId;
		
		/// <summary>
		/// 
		/// </summary>
        private UserInfo user;
		/// <summary>
		/// 
		/// </summary>
		private CompanyProductTypeInfo parent;
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PtName
		{
			get 
			{
				return this._ptName;
			}
			set 
			{
				this._ptName = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int InfoCount
		{
			get 
			{
				return this._infoCount;
			}
			set 
			{
				this._infoCount = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public long UserId
		{
			get 
			{
				return this._userId;
			}
			set 
			{
				this._userId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public long CompanyId
		{
			get 
			{
				return this._parentId;
			}
			set 
			{
				this._parentId = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
        public virtual UserInfo User
		{
			get
			{
				return this.user;
			}
			set
			{
				this.user = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public virtual CompanyProductTypeInfo Parent
		{
			get
			{
				return this.parent;
			}
			set
			{
				this.parent = value;
			}
			
		}
		#endregion

        public string Reamrk { get; set; }
    }
} 

