//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CreditLeavlInfo.autogenerated.cs
// author: wangzhen
// create date：2011-5-31 12:05:59
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
    public partial class CreditLeavlInfo
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private int _id;

        /// <summary>
        /// 
        /// </summary>
        private string _leavlName;

        /// <summary>
        /// 
        /// </summary>
        private int _leavl;

        /// <summary>
        /// 
        /// </summary>
        private int _upPoint = -1;

        /// <summary>
        /// 
        /// </summary>
        private int _downPoint;

        /// <summary>
        /// 
        /// </summary>
        private string _imagePath;


        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string LeavlName
        {
            get
            {
                return this._leavlName;
            }
            set
            {
                this._leavlName = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int Leavl
        {
            get
            {
                return this._leavl;
            }
            set
            {
                this._leavl = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int UpPoint
        {
            get
            {
                return this._upPoint;
            }
            set
            {
                this._upPoint = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int DownPoint
        {
            get
            {
                return this._downPoint;
            }
            set
            {
                this._downPoint = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ImagePath
        {
            get
            {
                return this._imagePath;
            }
            set
            {
                this._imagePath = value;
            }
        }

        #endregion
    }
}

