//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：FieldValueInfo.autogenerated.cs
// author: wangzhen
// create date：2011-5-11 12:15:17
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
	public partial class FieldValueInfo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private int _id;
		
		/// <summary>
		/// 
		/// </summary>
		private int _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private int _fieldId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _fieldValue;
		
		/// <summary>
		/// 
		/// </summary>
		private SupplyInfo product;
		/// <summary>
		/// 
		/// </summary>
		private FieldInfo field;
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int FieldId
		{
			get 
			{
				return this._fieldId;
			}
			set 
			{
				this._fieldId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string FieldValue
		{
			get 
			{
				return this._fieldValue;
			}
			set 
			{
				this._fieldValue = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual SupplyInfo Product
		{
			get
			{
				return this.product;
			}
			set
			{
				this.product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public virtual FieldInfo Field
		{
			get
			{
				return this.field;
			}
			set
			{
				this.field = value;
			}
			
		}
		#endregion
	}
} 

