//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：MeasuringUnitInfo.autogenerated.cs
// author: wangzhen
// create date：2011-3-29 16:18:42
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
	public partial class MeasuringUnitInfo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private int _id;
		
		/// <summary>
		/// 
		/// </summary>
		private string _measuringUnitName;
		
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string MeasuringUnitName
		{
			get 
			{
				return this._measuringUnitName;
			}
			set 
			{
				this._measuringUnitName = value;
			}
		}
	
		#endregion
	}
} 

