//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PageRecordInfo.autogenerated.cs
// author: wangzhen
// create date：2011-6-2 11:51:38
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
	public partial class PageRecordInfo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private int _id;
		
		/// <summary>
		/// 
		/// </summary>
		private string _guest;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime _date;
		
		/// <summary>
		/// 
		/// </summary>
		private int _userId;
		
		/// <summary>
		/// 
		/// </summary>
		private int _flag;
		
		/// <summary>
		/// 
		/// </summary>
		private int _flagInfo;
		
		/// <summary>
		/// 
		/// </summary>
		private string _iP;

        /// <summary>
        /// 
        /// </summary>
        private string _pageName;
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Guest
		{
			get 
			{
				return this._guest;
			}
			set 
			{
				this._guest = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public DateTime Date
		{
			get 
			{
				return this._date;
			}
			set 
			{
				this._date = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int UserId
		{
			get 
			{
				return this._userId;
			}
			set 
			{
				this._userId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int Flag
		{
			get 
			{
				return this._flag;
			}
			set 
			{
				this._flag = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int FlagInfo
		{
			get 
			{
				return this._flagInfo;
			}
			set 
			{
				this._flagInfo = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string IP
		{
			get 
			{
				return this._iP;
			}
			set 
			{
				this._iP = value;
			}
		}

        /// <summary>
        /// 
        /// </summary>
        public string PageName
        {
            get
            {
                return this._pageName;
            }
            set
            {
                this._pageName = value;
            }
        }
	
		#endregion
	}
} 

