//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：SlidesInfo.autogenerated.cs
// author: wangzhen
// create date：2011-6-1 17:01:52
//
//------------------------------------------------------------------------------
using System;
namespace XYECOM.Model
{
	public partial class SlidesInfo
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private int _id;
		
		/// <summary>
		/// 
		/// </summary>
		private int _userId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _link;
		
		/// <summary>
		/// 
		/// </summary>
		private string _slidesTitle;
		
		/// <summary>
		/// 
		/// </summary>
		private int _orderId;
		
		
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int UserId
		{
			get 
			{
				return this._userId;
			}
			set 
			{
				this._userId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Link
		{
			get 
			{
				return this._link;
			}
			set 
			{
				this._link = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string SlidesTitle
		{
			get 
			{
				return this._slidesTitle;
			}
			set 
			{
				this._slidesTitle = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int OrderId
		{
			get 
			{
				return this._orderId;
			}
			set 
			{
				this._orderId = value;
			}
		}
	
		#endregion
	}
} 

