<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.trade.index,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("    <title>");	XYBody.Append(tradename.ToString());	XYBody.Append("频道 - ");	XYBody.Append(config.webname);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=\"gb2312\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/channel.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");




	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");



	XYBody.Append("	<div class=\"search\">\r\n");
	XYBody.Append("		<div class=\"sh_tab\">\r\n");
	XYBody.Append("			<div class=\"order\">\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("keyword/\">订购固定排名</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<ul id=\"_xy_big_menu_box\">\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_index\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("\" class=\"tabactive\"><span>首 页</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_news\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("news/index.aspx\"><span>新闻资讯</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_offer\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("offer/index.aspx\"><span>产品中心</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_investment\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("investment/index.aspx\"><span>招商加盟</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_company\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("company/index.aspx\"><span>行业公司</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_job\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("job/index.aspx\"><span>人才招聘</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_brand\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("brand/index.aspx\"><span>行业品牌</span></a></li>				\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_exhibition\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("exhibition/index.aspx\"><span>展会信息</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_survey\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("survey/index.aspx\"><span>调查问卷</span></a></li>\r\n");
	XYBody.Append("				<li style=\"display:none;\"><a href=\"#\"><span>社区交流</span></a></li>\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</ul>\r\n");
	XYBody.Append("			<script type=\"text/javascript\">xy_Sel_CurBigMenu();</" + "script>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"sh_cnt\">\r\n");
	XYBody.Append("			<div id=\"main\">\r\n");
	XYBody.Append("				<input type=\"text\" id=\"txtsearchkey\" name=\"sch_text\" class=\"textsearch\" onkeydown=\"_xy_KeyPress('DoSearch');\"/>\r\n");
	XYBody.Append("				<div class=\"soSelect\" onclick=\"xy_ShowSearchMenu();\">\r\n");
	XYBody.Append("					<div class=\"option_current\" id=\"headSlected\" >产品</div>\r\n");
	XYBody.Append("					<div class=\"option_arrow\">\r\n");
	XYBody.Append("						<a href=\"#\"><span class=\"arrow\"></span></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("					<ul onmouseover=\"drop_mouseover('head')\" onmouseout=\"drop_mouseout('head');\" style=\"display: none;\" class=\"options\" id=\"headSel\">\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('产品','offer','sell');\">产品</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('求购','buy','buy');\">求购</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('招商','investment','sell');\">招商</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('加盟','investment','buy');\">加盟</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('融资','venture','sell');\">融资</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('服务','service','sell');\">服务</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('企业','company','sell');\">企业</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('资讯','news','');\">资讯</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('人才','job','');\">人才</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('品牌','brand','');\">品牌</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('展会','exhibition','');\">展会</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_FlagName\" value=\"offer\"/>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_InfoType\" value=\"sell\"/>\r\n");
	XYBody.Append("				<button value=\"搜索\" id=\"DoSearch\" name=\"DoSearch\" class=\"btsearch\" onclick=\"xy_search();\"/>搜索</button>\r\n");
	XYBody.Append("				<a href=\"/search/advanced_search.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[高级搜索]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("contributor.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[投稿]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("post.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[发布信息]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("baike/index.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[百科]</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"sch_bnr\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_5.jpg\" width=\"170\" height=\"77\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("			<div id=\"hot_schs\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("					<li><strong>热门搜索词：</strong></li>\r\n");
	XYBody.Append("					<li>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReMenSouSuoGuanjianzi").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</li>\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");


	XYBody.Append("	<div id=\"best_cmpy\">\r\n");
	XYBody.Append("		<ul>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_3.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_4.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_3.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_4.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_1.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("			<li><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_2.jpg\" width=\"191\" height=\"62\" alt=\"\" /></a></li>\r\n");
	XYBody.Append("		</ul>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"idx_cnt1\">\r\n");
	XYBody.Append("		<div id=\"mid\" style=\"margin-left:0;\">\r\n");
	XYBody.Append("			<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_2.jpg\" width=\"360\" height=\"194\" alt=\"\" /></a>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"left\" style=\"margin-left:6px;\">\r\n");
	XYBody.Append("			<div class=\"top spacer\"></div>\r\n");
	XYBody.Append("			<div class=\"main\">\r\n");
	XYBody.Append("				<div class=\"tit\"><h2><span>热点信息</span></h2></div>\r\n");
	XYBody.Append("				<ul class=\"hinfo-text\">\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_HangYe_HotMessage").ToString() + "\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("				<ul class=\"hinfo-img\">\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_HangYe_HotMessagePicture").ToString() + "\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"btm spacer\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"y_tab1\" class=\"\" onmouseover=\"xy_selectBox(2,1,'y','selected');\"><a target=\"_blank\" href=\"#\">名优企业</a></h2>\r\n");
	XYBody.Append("			    <h2 id=\"y_tab2\" class=\"selected\" onmouseout=\"xy_selectBox(2,2,'y','selected');\"><a target=\"_blank\" href=\"#\">最新企业</a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"y_box1\" class=\"Mblk_01\" style=\"display:none\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_HangYe_TopOffice").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"y_box2\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_HangYe_NewOffice").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div class=\"clr\"></div>\r\n");
	XYBody.Append("	<div id=\"idx_cnt2\">\r\n");
	XYBody.Append("		<div id=\"left\">\r\n");
	XYBody.Append("			<div id=\"offers\" style=\"margin:0;\">\r\n");
	XYBody.Append("				<div id=\"tit\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li class=\"current\" onmouseover=\"document.getElementById('remcd_offer').style.display='none';document.getElementById('remcd_supply').style.display='block';document.getElementById('tab_supply').className='current';document.getElementById('tab_offer').className='';\" id=\"tab_supply\">推荐供应</li>\r\n");
	XYBody.Append("						<li onmouseover=\"document.getElementById('remcd_supply').style.display='none';document.getElementById('remcd_offer').style.display='block';document.getElementById('tab_supply').className='';document.getElementById('tab_offer').className='current';\" id=\"tab_offer\">推荐求购</li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"remcd_supply\">\r\n");
	XYBody.Append("					<div id=\"pic_cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_GongYinPicture").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("						    " +  XYECOMCreateHTML("XY_HangYe_GongYin").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"hasty_offer\">\r\n");
	XYBody.Append("						<div class=\"h_lt\">紧急供应：</div>\r\n");
	XYBody.Append("						<div class=\"h_rt\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_GongYinJInJI").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"remcd_offer\" style=\"display:none;\">\r\n");
	XYBody.Append("					<div id=\"pic_cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_QiuGouPicture").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"cnts\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_QiuGou").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"hasty_offer\">\r\n");
	XYBody.Append("						<div class=\"h_lt\">紧急求购：</div>\r\n");
	XYBody.Append("						<div class=\"h_rt\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_QiuGouJinJi").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"area1\" style=\"margin-top:10px;margin-bottom:10px;\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_news\"><h2>热点资讯</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"info_lt\">\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_HangYe_HotZiXun").ToString() + "\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_HotZiXun1").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"info_rt\">\r\n");
	XYBody.Append("						<div class=\"Bm_1\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_HotZiXun2").ToString() + "\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"Bm_11\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_HotZiXun3").ToString() + "\r\n");
	XYBody.Append("							<ul class=\"Bm_12 fia\">\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_HotZiXun4").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("						<div class=\"Bm_13 fia\">\r\n");
	XYBody.Append("							<ul class=\"Bm_14\">\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_HotZiXun5").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("							<ul class=\"Bm_12\">\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_HotZiXun6").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"area1\" id=\"zs_area3\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_zs\"><h2>推荐招商</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"g_item\">\r\n");
	XYBody.Append("						<div class=\"gq_pics\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_ZhanShangPicture").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<ul class=\"clr\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_ZhanShang").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"area1\" id=\"zs_area4\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_jm\"><h2>推荐加盟</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"g_item\">\r\n");
	XYBody.Append("						<div class=\"gq_pics\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_JiaMengPicture").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<ul class=\"clr\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_JiaMeng").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("			<div class=\"area1\" id=\"zs_area3\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_zs\"><h2>推荐招商</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"g_item\">\r\n");
	XYBody.Append("						<div class=\"gq_pics\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_ZhanShangPicture").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<ul class=\"clr\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_ZhanShang").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"area1\" id=\"zs_area4\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_jm\"><h2>推荐加盟</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"g_item\">\r\n");
	XYBody.Append("						<div class=\"gq_pics\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_HangYe_JiaMengPicture").ToString() + "\r\n");
	XYBody.Append("								</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<ul class=\"clr\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_HangYe_ZhanShang").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\"><strong>产品分类：</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\" style=\"width:268px;overflow:hidden;\">\r\n");
	XYBody.Append("				<div class=\"cnt\" id=\"price\">\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("					<dl>\r\n");
	XYBody.Append("						<dt><h4><a href=\"\">笔记本电脑</a></h4></dt>\r\n");
	XYBody.Append("						<dd>\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li>联想</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>惠普</li>\r\n");
	XYBody.Append("								<li>华硕</li>\r\n");
	XYBody.Append("								<li>东芝</li>\r\n");
	XYBody.Append("								<li>IBM</li>\r\n");
	XYBody.Append("								<li>戴尔</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</dd>\r\n");
	XYBody.Append("					</dl>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"bnr_b1\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_10.jpg\" width=\"270\" height=\"75\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("			<div id=\"gold_user\">\r\n");
	XYBody.Append("				<div class=\"top\">\r\n");
	XYBody.Append("					<div class=\"tit\"><span class=\"fright\">更多></span><h2>金牌商家展示</h2></div>\r\n");
	XYBody.Append("					<div class=\"slogan\"><a href=\"\" class=\"red big\"><strong>马上入住金牌商家，商机无限>></strong></a></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"slidetexts\" class=\"mid\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_Index_JinPaiShangJiaZhanShi").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<script type=\"text/javascript\">\r\n");
	XYBody.Append("				<!--\r\n");
	XYBody.Append("					try{\r\n");
	XYBody.Append("					 slideLine('slidetexts', 3000, 5, 40);\r\n");
	XYBody.Append("					}catch(e) {}\r\n");
	XYBody.Append("				//-->\r\n");
	XYBody.Append("				</" + "script>\r\n");
	XYBody.Append("				<div class=\"btm spacer\"></div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\" style=\"margin-top:8px;\">\r\n");
	XYBody.Append("				<h2 id=\"x_tab1\" class=\"\" onmouseover=\"xy_selectBox(2,1,'x','selected');\"><a target=\"_blank\" href=\"#\">名优企业</a></h2>\r\n");
	XYBody.Append("		    	<h2 id=\"x_tab2\" class=\"selected\" onmouseout=\"xy_selectBox(2,2,'x','selected');\"><a target=\"_blank\" href=\"#\">最新企业</a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"x_box1\" class=\"Mblk_01\" style=\"display:none\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_HangYe_TopOffice").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("	        <div id=\"x_box2\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_HangYe_NewOffice").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>			\r\n");
	XYBody.Append("	<div class=\"hy_brand clr\">\r\n");
	XYBody.Append("		<div class=\"tit\">行业推荐品牌</div>\r\n");
	XYBody.Append("		<div class=\"brand_pic\">\r\n");
	XYBody.Append("		    <ul>\r\n");
	XYBody.Append("		    " +  XYECOMCreateHTML("XY_Index_HangYePinPai").ToString() + "\r\n");
	XYBody.Append("		    </ul>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
