//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CompanyProductTypeAccess.autogenerated.cs
// author: wangzhen
// create date：2011-3-29 16:31:07
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using XYECOM.Core.Data;

namespace XYECOM.SQLServer
{
    public partial class CompanyProductTypeAccess
    {

        /// <summary>
        /// 根据Id获取实体信息
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>数据实体对象</returns>
        public XYECOM.Model.CompanyProductTypeInfo GetItem(int infoId)
        {
            XYECOM.Model.CompanyProductTypeInfo info = null;
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "select * from XY_CompanyProductType where Id = @Id";
            using (SqlDataReader reader = SqlHelper.ExecuteReader(CommandType.Text, sql, parame))
            {
                if (reader.Read())
                {
                    info = new XYECOM.Model.CompanyProductTypeInfo();
                    info.Id = Core.MyConvert.GetInt32(reader["Id"].ToString());
                    info.PtName = reader["PtName"].ToString();
                    info.InfoCount = Core.MyConvert.GetInt32(reader["InfoCount"].ToString());
                    info.UserId = Core.MyConvert.GetInt32(reader["UserId"].ToString());
                    info.CompanyId = Core.MyConvert.GetInt32(reader["ParentId"].ToString());
                    info.Reamrk = reader["remark"].ToString();
                }
            }
            return info;
        }

        public XYECOM.Model.CompanyProductTypeInfo GetItem(int infoId, int userId)
        {
            XYECOM.Model.CompanyProductTypeInfo info = null;
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId),
                new SqlParameter("@userid",userId)
			};
            string sql = "select * from XY_CompanyProductType where Id = @Id and UserId=@userid";
            using (SqlDataReader reader = SqlHelper.ExecuteReader(CommandType.Text, sql, parame))
            {
                if (reader.Read())
                {
                    info = new XYECOM.Model.CompanyProductTypeInfo();
                    info.Id = Core.MyConvert.GetInt32(reader["Id"].ToString());
                    info.PtName = reader["PtName"].ToString();
                    info.InfoCount = Core.MyConvert.GetInt32(reader["InfoCount"].ToString());
                    info.UserId = Core.MyConvert.GetInt32(reader["UserId"].ToString());
                    info.CompanyId = Core.MyConvert.GetInt32(reader["ParentId"].ToString());
                    info.Reamrk = reader["remark"].ToString();
                }
            }
            return info;
        }

        /// <summary>
        /// 删除操作(删除单条)
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>受影响的行数</returns>
        public int Delete(int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "delete XY_CompanyProductType where Id = @Id;";
            sql += "update CaseInfo set CaseTypeId=0,CaseTypeName='默认分类' where CaseTpyeId =" + infoId;
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 删除操作(删除多条)
        /// </summary>
        /// <param name="infoIds">以逗号隔开的主键Id集合</param>
        /// <returns>受影响的行数</returns>
        public int DeleteByIds(string infoIds)
        {

            string sql = "delete XY_CompanyProductType where Id in (" + infoIds + ");";
            sql += "update CaseInfo set CaseTypeId=0,CaseTypeName='默认分类' where CaseTypeId in (" + infoIds +
            ")";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, null);
        }


        /// <summary>
        /// 修改操作
        /// </summary>
        /// <param name="info">实体对象</param>
        /// <returns>受影响行数</returns>
        public int Update(XYECOM.Model.CompanyProductTypeInfo info)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",info.Id),
				new SqlParameter("@PtName",info.PtName),
				new SqlParameter("@InfoCount",info.InfoCount),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@ParentId",info.CompanyId),
				new SqlParameter("@remark",info.Reamrk)	
			};

            string sql = "update XY_CompanyProductType set ";
            sql += "PtName=@PtName,";
            sql += "InfoCount=@InfoCount,";
            sql += "UserId=@UserId,";
            sql += "ParentId=@ParentId";
            sql += "remark=@remark";
            sql += " where Id = @Id";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }

        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.CompanyProductTypeInfo info)
        {
            //判断要添加的信息是否存在
            string where = string.Format(" where PtName='{0}' and ParentId={1}", info.PtName, info.CompanyId);
            int num = Count(where);
            if (num > 0)
            {
                return -1;
            }
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@PtName",info.PtName),
				new SqlParameter("@InfoCount",info.InfoCount),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@ParentId",info.CompanyId),
				new SqlParameter("@remark",info.Reamrk)	
			};

            string sql = "INSERT INTO XY_CompanyProductType (";
            sql += "PtName,";
            sql += "InfoCount,";
            sql += "UserId,";
            sql += "ParentId,remark) values (";
            sql += "@PtName,";
            sql += "@InfoCount,";
            sql += "@UserId,";
            sql += "@ParentId,@remark)";

            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <param name="ceInfoid">新增信息的ID</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.CompanyProductTypeInfo info, out int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",SqlDbType.Int),
				new SqlParameter("@PtName",info.PtName),
				new SqlParameter("@InfoCount",info.InfoCount),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@ParentId",info.CompanyId),
				new SqlParameter("@remark",info.Reamrk)	
			};
            parame[0].Direction = ParameterDirection.Output;
            string sql = "INSERT INTO XY_CompanyProductType (";
            sql += "PtName,";
            sql += "InfoCount,";
            sql += "UserId,";
            sql += "ParentId) values (";
            sql += "@PtName,";
            sql += "@InfoCount,";
            sql += "@UserId,";
            sql += "@ParentId);select @Id=ident_current('XY_CompanyProductType');";

            int rowAffected = SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);

            if (rowAffected >= 0)
            {
                if (parame[0].Value != null && parame[0].Value.ToString() != "")
                    infoId = Core.MyConvert.GetInt32(parame[0].Value.ToString());
                else
                    infoId = 0;
            }
            else
            {
                infoId = -1;
            }
            return rowAffected;
        }


        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <returns>多条记录</returns>
        public DataTable Select()
        {
            string sql = "select * from XY_CompanyProductType";
            return SqlHelper.ExecuteTable(sql);
        }
        /*
        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <param name="pinfo">分页条件</param>
        /// <returns>多条记录</returns>
        public DataTable GetDataTable(XYECOM.Model.PageInfo pagingDescription)
        {			
            string sql = "SELECT * FROM ("+
                    "SELECT "+pagingDescription.Columns+", row_number() over(order by "+pagingDescription.OrderStatement+") rownumber"+
                    "FROM XY_CompanyProductType where "+pagingDescription.Condition+") t"+
                    "WHERE t.rownumber between "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + 1 and  "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + "+pagingDescription.PageSize;
			
            DataTable data = new DataTable();
            data = SqlHelper.ExecuteTable(sql);
            pagingDescription.Total = data.Rows.Count;
            return data;
        }
        */
        //符合条件的总条数
        public int Count(string strWhere)
        {
            string sql = "select count(*) from XY_CompanyProductType " + strWhere;
            return (int)SqlHelper.ExecuteScalar(sql);
        }
    }
}
