//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：FieldValueAccess.autogenerated.cs
// author: wangzhen
// create date：2011-5-11 12:15:18
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using XYECOM.Core.Data;

namespace XYECOM.SQLServer
{
    public partial class FieldValueAccess
    {
		
		/// <summary>
        	/// 根据Id获取实体信息
        	/// </summary>
        	/// <param name="infoId">信息主键Id</param>
        	/// <returns>数据实体对象</returns>
		public XYECOM.Model.FieldValueInfo GetItem(int infoId)
		{
			XYECOM.Model.FieldValueInfo info = null;
			SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
			string sql = "select * from XY_FieldValue where Id = @Id";
			using (SqlDataReader reader = SqlHelper.ExecuteReader(CommandType.Text, sql, parame))
			{
				if (reader.Read())
				{
					info =  new XYECOM.Model.FieldValueInfo();
					info.Id= Core.MyConvert.GetInt32(reader["Id"].ToString());
					info.ProductId= Core.MyConvert.GetInt32(reader["ProductId"].ToString());
					info.FieldId= Core.MyConvert.GetInt32(reader["FieldId"].ToString());
					info.FieldValue= reader["FieldValue"].ToString();
				}
			}
			return info;
		}
		
		/// <summary>
		/// 删除操作(删除单条)
		/// </summary>
		/// <param name="infoId">信息主键Id</param>
		/// <returns>受影响的行数</returns>
		public int Delete(int infoId)
		{
			SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
			string sql = "delete XY_FieldValue where Id = @Id";
			return SqlHelper.ExecuteNonQuery(CommandType.Text, sql,parame);
		}
		

		/// <summary>
		/// 删除操作(删除多条)
		/// </summary>
		/// <param name="infoIds">以逗号隔开的主键Id集合</param>
		/// <returns>受影响的行数</returns>
		public int DeleteByIds(string infoIds)
		{
			string sql = "delete XY_FieldValue where Id in ("+infoIds+")";
			return SqlHelper.ExecuteNonQuery(CommandType.Text, sql,null);
		}
		

		/// <summary>
		/// 修改操作
		/// </summary>
		/// <param name="info">实体对象</param>
		/// <returns>受影响行数</returns>
		public int Update(XYECOM.Model.FieldValueInfo info)
		{
			SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",info.Id),
				new SqlParameter("@ProductId",info.ProductId),
				new SqlParameter("@FieldId",info.FieldId),
				new SqlParameter("@FieldValue",info.FieldValue)	
			};
			
			string sql = "update XY_FieldValue set ";
			sql += "ProductId=@ProductId,";
			sql += "FieldId=@FieldId,";
			sql += "FieldValue=@FieldValue";
			sql += " where Id = @Id";
			return  SqlHelper.ExecuteNonQuery(CommandType.Text,sql, parame);
		}		
		
		/// <summary>
		/// 插入操作
		/// </summary>
		/// <param name="info">要插入的实体对象</param>
		/// <returns></returns>
		public int Insert(XYECOM.Model.FieldValueInfo info)
		{
			SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@ProductId",info.ProductId),
				new SqlParameter("@FieldId",info.FieldId),
				new SqlParameter("@FieldValue",info.FieldValue)	
			};
			
			string sql = "INSERT INTO XY_FieldValue (";
			sql += "ProductId,";
			sql += "FieldId,";
			sql += "FieldValue) values (";
			sql += "@ProductId,";
			sql += "@FieldId,";
			sql += "@FieldValue)";
			
			return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
		}
		
		
		/// <summary>
		/// 插入操作
		/// </summary>
		/// <param name="info">要插入的实体对象</param>
		/// <param name="ceInfoid">新增信息的ID</param>
		/// <returns></returns>
		public int Insert(XYECOM.Model.FieldValueInfo info,out int infoId)
		{
			SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",SqlDbType.Int),
				new SqlParameter("@ProductId",info.ProductId),
				new SqlParameter("@FieldId",info.FieldId),
				new SqlParameter("@FieldValue",info.FieldValue),
			};
			parame[0].Direction = ParameterDirection.Output;
			string sql = "INSERT INTO XY_FieldValue (";
			sql += "ProductId,";
			sql += "FieldId,";
			sql += "FieldValue) values (";
			sql += "@ProductId,";
			sql += "@FieldId,";
			sql += "@FieldValue);select @Id=ident_current('XY_FieldValue')";
			
			int rowAffected = SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);

			if (rowAffected >= 0)
			{
				if (parame[0].Value != null && parame[0].Value.ToString() != "")
					infoId = Core.MyConvert.GetInt32(parame[0].Value.ToString());
				else
					infoId = 0;
			}
			else
			{
				infoId = -1;
			}
			return rowAffected;
		}
		
		
		/// <summary>
		/// 获取多条记录
		/// </summary>
		/// <returns>多条记录</returns>
		public DataTable Select()
		{
			string sql = "select * from XY_FieldValue";
			return SqlHelper.ExecuteTable(sql);
		}
		/*
		/// <summary>
		/// 获取多条记录
		/// </summary>
		/// <param name="pinfo">分页条件</param>
		/// <returns>多条记录</returns>
		public DataTable GetDataTable(XYECOM.Model.PageInfo pagingDescription)
		{			
			string sql = "SELECT * FROM ("+
					"SELECT "+pagingDescription.Columns+", row_number() over(order by "+pagingDescription.OrderStatement+") rownumber"+
					"FROM XY_FieldValue where "+pagingDescription.Condition+") t"+
					"WHERE t.rownumber between "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + 1 and  "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + "+pagingDescription.PageSize;
			
			DataTable data = new DataTable();
			data = SqlHelper.ExecuteTable(sql);
			pagingDescription.Total = data.Rows.Count;
			return data;
		}
		*/
		//符合条件的总条数
		public int Count(string strWhere)
		{
			string sql = "select count(*) from XY_FieldValue "+strWhere;
        		return (int)SqlHelper.ExecuteScalar(sql);
		}
    }
}
