//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PageRecordAccess.autogenerated.cs
// author: wangzhen
// create date：2011-6-2 11:51:40
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using XYECOM.Core.Data;

namespace XYECOM.SQLServer
{
    public partial class PageRecordAccess
    {

        /// <summary>
        /// 根据Id获取实体信息
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>数据实体对象</returns>
        public XYECOM.Model.PageRecordInfo GetItem(int infoId)
        {
            XYECOM.Model.PageRecordInfo info = null;
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "select * from XY_PageRecord where Id = @Id";
            using (SqlDataReader reader = SqlHelper.ExecuteReader(CommandType.Text, sql, parame))
            {
                if (reader.Read())
                {
                    info = new XYECOM.Model.PageRecordInfo();
                    info.Id = Core.MyConvert.GetInt32(reader["Id"].ToString());
                    info.Guest = reader["Guest"].ToString();
                    info.Date = Core.MyConvert.GetDateTime(reader["Date"].ToString());
                    info.UserId = Core.MyConvert.GetInt32(reader["UserId"].ToString());
                    info.Flag = Core.MyConvert.GetInt32(reader["Flag"].ToString());
                    info.FlagInfo = Core.MyConvert.GetInt32(reader["FlagInfo"].ToString());
                    info.IP = reader["IP"].ToString();
                }
            }
            return info;
        }

        /// <summary>
        /// 删除操作(删除单条)
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>受影响的行数</returns>
        public int Delete(int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "delete XY_PageRecord where Id = @Id";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 删除操作(删除多条)
        /// </summary>
        /// <param name="infoIds">以逗号隔开的主键Id集合</param>
        /// <returns>受影响的行数</returns>
        public int DeleteByIds(string infoIds)
        {
            string sql = "delete XY_PageRecord where Id in (" + infoIds + ")";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, null);
        }


        /// <summary>
        /// 修改操作
        /// </summary>
        /// <param name="info">实体对象</param>
        /// <returns>受影响行数</returns>
        public int Update(XYECOM.Model.PageRecordInfo info)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",info.Id),
				new SqlParameter("@Guest",info.Guest),
				new SqlParameter("@Date",info.Date),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Flag",info.Flag),
				new SqlParameter("@FlagInfo",info.FlagInfo),
				new SqlParameter("@IP",info.IP),
	            new SqlParameter("@PageName",info.PageName)
			};

            string sql = "update XY_PageRecord set ";
            sql += "Guest=@Guest,";
            sql += "Date=@Date,";
            sql += "UserId=@UserId,";
            sql += "Flag=@Flag,";
            sql += "FlagInfo=@FlagInfo,";
            sql += "IP=@IP,";
            sql += "PageName=@PageName";
            sql += " where Id = @Id";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }

        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.PageRecordInfo info)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Guest",info.Guest),
				new SqlParameter("@Date",info.Date),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Flag",info.Flag),
				new SqlParameter("@FlagInfo",info.FlagInfo),
				new SqlParameter("@IP",info.IP),
	            new SqlParameter("@PageName",info.PageName)
			};

            string sql = "INSERT INTO XY_PageRecord (";
            sql += "Guest,";
            sql += "Date,";
            sql += "UserId,";
            sql += "Flag,";
            sql += "FlagInfo,";
            sql += "IP,";
            sql += "PageName) values (";
            sql += "@Guest,";
            sql += "@Date,";
            sql += "@UserId,";
            sql += "@Flag,";
            sql += "@FlagInfo,";
            sql += "@IP,";
            sql += "@PageName)";

            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <param name="ceInfoid">新增信息的ID</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.PageRecordInfo info, out int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",SqlDbType.Int),
				new SqlParameter("@Guest",info.Guest),
				new SqlParameter("@Date",info.Date),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Flag",info.Flag),
				new SqlParameter("@FlagInfo",info.FlagInfo),
				new SqlParameter("@IP",info.IP),
	            new SqlParameter("@PageName",info.PageName)
			};
            parame[0].Direction = ParameterDirection.Output;
            string sql = "INSERT INTO XY_PageRecord (";
            sql += "Guest,";
            sql += "Date,";
            sql += "UserId,";
            sql += "Flag,";
            sql += "FlagInfo,";
            sql += "IP,";
            sql += "PageName) values (";
            sql += "@Guest,";
            sql += "@Date,";
            sql += "@UserId,";
            sql += "@Flag,";
            sql += "@FlagInfo,";
            sql += "@IP,";
            sql += "@PageName);select @Id=ident_current('XY_PageRecord')";

            int rowAffected = SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);

            if (rowAffected >= 0)
            {
                if (parame[0].Value != null && parame[0].Value.ToString() != "")
                    infoId = Core.MyConvert.GetInt32(parame[0].Value.ToString());
                else
                    infoId = 0;
            }
            else
            {
                infoId = -1;
            }
            return rowAffected;
        }


        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <returns>多条记录</returns>
        public DataTable Select()
        {
            string sql = "select * from XY_PageRecord";
            return SqlHelper.ExecuteTable(sql);
        }
        /*
        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <param name="pinfo">分页条件</param>
        /// <returns>多条记录</returns>
        public DataTable GetDataTable(XYECOM.Model.PageInfo pagingDescription)
        {			
            string sql = "SELECT * FROM ("+
                    "SELECT "+pagingDescription.Columns+", row_number() over(order by "+pagingDescription.OrderStatement+") rownumber"+
                    "FROM XY_PageRecord where "+pagingDescription.Condition+") t"+
                    "WHERE t.rownumber between "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + 1 and  "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + "+pagingDescription.PageSize;
			
            DataTable data = new DataTable();
            data = SqlHelper.ExecuteTable(sql);
            pagingDescription.Total = data.Rows.Count;
            return data;
        }
        */
        //符合条件的总条数
        public int Count(string strWhere)
        {
            string sql = "select count(*) from XY_PageRecord " + strWhere;
            return (int)SqlHelper.ExecuteScalar(sql);
        }
    }
}
