//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：SlidesAccess.autogenerated.cs
// author: wangzhen
// create date：2011-6-1 17:01:53
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using XYECOM.Core.Data;

namespace XYECOM.SQLServer
{
    public partial class SlidesAccess
    {

        /// <summary>
        /// 根据Id获取实体信息
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>数据实体对象</returns>
        public XYECOM.Model.SlidesInfo GetItem(int infoId)
        {
            XYECOM.Model.SlidesInfo info = null;
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "select * from XY_Slides where Id = @Id";
            using (SqlDataReader reader = SqlHelper.ExecuteReader(CommandType.Text, sql, parame))
            {
                if (reader.Read())
                {
                    info = new XYECOM.Model.SlidesInfo();
                    info.Id = Core.MyConvert.GetInt32(reader["Id"].ToString());
                    info.UserId = Core.MyConvert.GetInt32(reader["UserId"].ToString());
                    info.Link = reader["Link"].ToString();
                    info.SlidesTitle = reader["SlidesTitle"].ToString();
                    info.OrderId = Core.MyConvert.GetInt32(reader["OrderId"].ToString());
                }
            }
            return info;
        }

        /// <summary>
        /// 删除操作(删除单条)
        /// </summary>
        /// <param name="infoId">信息主键Id</param>
        /// <returns>受影响的行数</returns>
        public int Delete(int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",infoId)
			};
            string sql = "delete XY_Slides where Id = @Id";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 删除操作(删除多条)
        /// </summary>
        /// <param name="infoIds">以逗号隔开的主键Id集合</param>
        /// <returns>受影响的行数</returns>
        public int DeleteByIds(string infoIds)
        {
            string sql = "delete XY_Slides where Id in (" + infoIds + ")";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, null);
        }


        /// <summary>
        /// 修改操作
        /// </summary>
        /// <param name="info">实体对象</param>
        /// <returns>受影响行数</returns>
        public int Update(XYECOM.Model.SlidesInfo info)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",info.Id),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Link",info.Link),
				new SqlParameter("@SlidesTitle",info.SlidesTitle),
				new SqlParameter("@OrderId",info.OrderId)	
			};

            string sql = "update XY_Slides set ";
            sql += "UserId=@UserId,";
            sql += "Link=@Link,";
            sql += "SlidesTitle=@SlidesTitle,";
            sql += "OrderId=@OrderId";
            sql += " where Id = @Id";
            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }

        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.SlidesInfo info)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Link",info.Link),
				new SqlParameter("@SlidesTitle",info.SlidesTitle),
				new SqlParameter("@OrderId",info.OrderId)	
			};

            string sql = "INSERT INTO XY_Slides (";
            sql += "UserId,";
            sql += "Link,";
            sql += "SlidesTitle,";
            sql += "OrderId) values (";
            sql += "@UserId,";
            sql += "@Link,";
            sql += "@SlidesTitle,";
            sql += "@OrderId)";

            return SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);
        }


        /// <summary>
        /// 插入操作
        /// </summary>
        /// <param name="info">要插入的实体对象</param>
        /// <param name="ceInfoid">新增信息的ID</param>
        /// <returns></returns>
        public int Insert(XYECOM.Model.SlidesInfo info, out int infoId)
        {
            SqlParameter[] parame = new SqlParameter[]
			{
				new SqlParameter("@Id",SqlDbType.Int),
				new SqlParameter("@UserId",info.UserId),
				new SqlParameter("@Link",info.Link),
				new SqlParameter("@SlidesTitle",info.SlidesTitle),
				new SqlParameter("@OrderId",info.OrderId),
			};
            parame[0].Direction = ParameterDirection.Output;
            string sql = "INSERT INTO XY_Slides (";
            sql += "UserId,";
            sql += "Link,";
            sql += "SlidesTitle,";
            sql += "OrderId) values (";
            sql += "@UserId,";
            sql += "@Link,";
            sql += "@SlidesTitle,";
            sql += "@OrderId);select @Id=ident_current('XY_Slides')";

            int rowAffected = SqlHelper.ExecuteNonQuery(CommandType.Text, sql, parame);

            if (rowAffected >= 0)
            {
                if (parame[0].Value != null && parame[0].Value.ToString() != "")
                    infoId = Core.MyConvert.GetInt32(parame[0].Value.ToString());
                else
                    infoId = 0;
            }
            else
            {
                infoId = -1;
            }
            return rowAffected;
        }


        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <returns>多条记录</returns>
        public DataTable Select()
        {
            string sql = "select * from XY_Slides";
            return SqlHelper.ExecuteTable(sql);
        }
        /*
        /// <summary>
        /// 获取多条记录
        /// </summary>
        /// <param name="pinfo">分页条件</param>
        /// <returns>多条记录</returns>
        public DataTable GetDataTable(XYECOM.Model.PageInfo pagingDescription)
        {			
            string sql = "SELECT * FROM ("+
                    "SELECT "+pagingDescription.Columns+", row_number() over(order by "+pagingDescription.OrderStatement+") rownumber"+
                    "FROM XY_Slides where "+pagingDescription.Condition+") t"+
                    "WHERE t.rownumber between "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + 1 and  "+pagingDescription.PageSize+" * ("+pagingDescription.PageIndex+" - 1) + "+pagingDescription.PageSize;
			
            DataTable data = new DataTable();
            data = SqlHelper.ExecuteTable(sql);
            pagingDescription.Total = data.Rows.Count;
            return data;
        }
        */
        //符合条件的总条数
        public int Count(string strWhere)
        {
            string sql = "select count(*) from XY_Slides " + strWhere;
            return (int)SqlHelper.ExecuteScalar(sql);
        }
    }
}
