<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.register,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);

	if (pageinfo.PageError==1)
	{


	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("<title>消息提示</title>\r\n");
	XYBody.Append("");	XYBody.Append(pageinfo.Meta);	XYBody.Append("\r\n");
	XYBody.Append("<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body style=\"background-color:#f2f2f2\">\r\n");
	XYBody.Append("<div id=\"sysMsgbox\">\r\n");
	XYBody.Append("	<ul>\r\n");
	XYBody.Append("	    <li class=\"msg\">");	XYBody.Append(pageinfo.MsgboxText);	XYBody.Append("</li>\r\n");
	XYBody.Append("        <li><a href=\"");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("\">");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("</a></li>\r\n");
	XYBody.Append("         <li><a href=\"#\" onclick=\"history.back();\">返回继续操作</a></li>\r\n");
	XYBody.Append("        <li><a href=\"/\">返回首页</a> | <a href=\"#\" onclick=\"window.close();\">关闭本页</a></li>\r\n");
	XYBody.Append("    </ul>\r\n");
	XYBody.Append("    <div id=\"r_f\">2000-2009　" +  XYECOMCreateHTML("XY_Copyright").ToString() + "　版权所有　纵横易商软件</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");



	Response.Write(XYBody.ToString());
System.Web.HttpContext.Current.Response.End();
	

	}	//end if

	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");

	XYBody.Append("    <title>");	XYBody.Append(seo.Title);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"");	XYBody.Append(seo.Description);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"");	XYBody.Append(seo.Keywords);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html;\" charset=\"gb2312\" />	\r\n");
	XYBody.Append("	<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/XYLib.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/Survey.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/validate.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />	\r\n");


	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/login.css\" rel=\"stylesheet\"\r\n");
	XYBody.Append("        type=\"text/css\" />\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/register.js\"\r\n");
	XYBody.Append("        language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body onload=\"");	XYBody.Append(pageinfo.OnLoadEvents);	XYBody.Append("\">\r\n");
	XYBody.Append("    <div id=\"wrapper\">\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");


	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <br />\r\n");
	XYBody.Append("        <div id=\"reg_nav\">\r\n");
	XYBody.Append("            <strong>您现在的位置：</strong> <a href=\"\" class=\"blue\">网站首页</a> &raquo; <a href=\"\" class=\"blue\">\r\n");
	XYBody.Append("                会员注册</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"regBg\">\r\n");
	XYBody.Append("            <form action=\"\" method=\"post\" id=\"frmRegister\">\r\n");
	XYBody.Append("            <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"6\" cellspacing=\"0\">\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\" valign=\"top\" width=\"130\" style=\"padding-top: 12px;\" align=\"left\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">用户类型</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"293\" valign=\"top\">\r\n");
	XYBody.Append("                        <input type=\"radio\" name=\"usertype\" value=\"enterprise\" checked=\"true\" onclick=\"displayDiv();\" />企业/个体经营会员\r\n");
	XYBody.Append("                        <input type=\"radio\" name=\"usertype\" value=\"individual\" onclick=\"displayDiv();\" />个人会员\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"432\" valign=\"top\">\r\n");
	XYBody.Append("                        <div id=\"Div1\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        请选择注册会员类型。\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\" align=\"left\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">会员登录名</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"293\" valign=\"top\">\r\n");
	XYBody.Append("                        <input name=\"loginname\" type=\"text\" size=\"31\" onblur=\"chktxt('0');\" onfocus=\"f('0');\"\r\n");
	XYBody.Append("                            id=\"loginname\" maxlength=\"20\" class=\"regOutInput\" /><br />\r\n");
	XYBody.Append("                        <span id=\"a\"></span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"432\" valign=\"top\" id=\"txt0\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        <em>4-15</em>位；数字(0-9)或英文(a-z),不支持中文；注册成功后不可修改\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr id=\"ulTrade\">\r\n");
	XYBody.Append("                    <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\" align=\"left\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">所属行业</strong><span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"293\" valign=\"top\">\r\n");
	XYBody.Append("                        <span id=\"divTrade\"></span>\r\n");
	XYBody.Append("                        <input type=\"hidden\" id=\"tradeid\" name=\"tradeid\" />\r\n");
	XYBody.Append("                        <script type=\"text/javascript\">\r\n");
	XYBody.Append("                var clsTrade = new ClassTypes(\"clsTrade\",'trade','divTrade','tradeid',\"tradeid\",");	XYBody.Append(config.CanChooseTradeNumber);	XYBody.Append(");\r\n");
	XYBody.Append("                clsTrade.Init();\r\n");
	XYBody.Append("                        </" + "script>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td width=\"432\" valign=\"top\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        请选择企业所在的行业\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">密 码</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td valign=\"top\">\r\n");
	XYBody.Append("                        <input name=\"password\" type=\"password\" size=\"31\" onblur=\"chktxt('1');\" onfocus=\"f('1');\"\r\n");
	XYBody.Append("                            id=\"password\" maxlength=\"20\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td valign=\"top\" id=\"txt1\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        <em>6-20</em>位，不能与用户名相同； 建议为英文字母(a-z)和数字(0-9)结合\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">重复输入密码</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"repassword\" type=\"password\" size=\"31\" onblur=\"chktxt('2');\" onfocus=\"f('2');\"\r\n");
	XYBody.Append("                            id=\"repassword\" maxlength=\"20\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td id=\"txt2\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        请再输入一遍您上面填写的密码。\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">电子邮箱</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"email\" type=\"text\" size=\"31\" id=\"email\" onblur=\"chktxt('5');\" onfocus=\"f('5');\"\r\n");
	XYBody.Append("                            maxlength=\"30\" class=\"regOutInput\" /><br />\r\n");
	XYBody.Append("                        <span id=\"spanemail\"></span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td id=\"txt5\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        重要！请务必填写真实,注册后不可更改，用于密码找回！\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">密码提示问题</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"question\" type=\"text\" onblur=\"chktxt('3');\" onfocus=\"f('3');\" id=\"question\"\r\n");
	XYBody.Append("                            maxlength=\"20\" size=\"31\" class=\"regOutInput\" /><span id=\"span1\">\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td class=\"regOutTip\" id=\"txt3\">\r\n");
	XYBody.Append("                        请填写自己最熟悉的问题，最少6位\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">密码提示答案</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"answer\" type=\"text\" size=\"31\" id=\"answer\" onblur=\"chktxt('4');\" onfocus=\"f('4');\"\r\n");
	XYBody.Append("                            maxlength=\"20\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td id=\"txt4\" class=\"regOutTip\">\r\n");
	XYBody.Append("                        密码提示答案不能与密码提示问题相同，最少6位\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");

	if (config.IsEnabledVCode("register"))
	{

	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                        <strong class=\"Font14_1\">验证码</strong> <span class=\"red\">*</span>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        ");	XYBody.Append(pageinfo.GetValidateCodeHTML());	XYBody.Append("\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");

	}	//end if

	XYBody.Append("                <!--简洁模式下显示提交按钮-->\r\n");

	if (config.regmode!="full")
	{

	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"agreement\" id=\"agreement\" type=\"checkbox\" value=\"on\" checked=\"checked\"\r\n");
	XYBody.Append("                            onclick=\"isAgreement(this);\" />我同意各项服务条款&nbsp;&nbsp;<a target=\"_blank\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("agreement.htm\">点此阅读</a>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");
	XYBody.Append("                <tr>\r\n");
	XYBody.Append("                    <td align=\"right\">\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                        <input name=\"\" type=\"button\" value=\" 提交 \" id=\"btnBasicSubmit\" onclick=\"return NormalModelRegUser();\" />&nbsp;&nbsp;<input\r\n");
	XYBody.Append("                            name=\"\" type=\"reset\" value=\" 取消 \" id=\"Reset4\" onclick=\"window.location.href='");	XYBody.Append(config.WebURL);	XYBody.Append("index.");	XYBody.Append(config.Suffix);	XYBody.Append("'\" />\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                    <td>\r\n");
	XYBody.Append("                    </td>\r\n");
	XYBody.Append("                </tr>\r\n");

	}	//end if

	XYBody.Append("            </table>\r\n");
	XYBody.Append("            <div id=\"infomation\">\r\n");
	XYBody.Append("                <!--高级模式-->\r\n");

	if (config.regmode=="full")
	{

	XYBody.Append("                <!-- 公司详细注册开始 -->\r\n");
	XYBody.Append("                <div id=\"company1\">\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td height=\"26\" align=\"right\" style=\"border-bottom: 1px solid #ccc;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">姓名和联系方式</strong>&nbsp;&nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"6\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td width=\"130\" align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">真实姓名：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td width=\"293\">\r\n");
	XYBody.Append("                                <input name=\"linkman\" type=\"text\" id=\"linkman\" maxlength=\"20\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"LinkuserMsg\" class=\"regOutTip\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">性别：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"sex\" type=\"radio\" value=\"1\" checked=\"checked\" />先生\r\n");
	XYBody.Append("                                <input name=\"sex\" type=\"radio\" value=\"0\" />女士\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">固定电话：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"telephone\" maxlength=\"50\" name=\"telephone\" size=\"50\" type=\"text\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                多个之间用,号隔开,格式：010-88888888-86 或 010-88888888\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">传真：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\">\r\n");
	XYBody.Append("                                <input id=\"fax\" maxlength=\"50\" name=\"fax\" size=\"50\" type=\"text\" class=\"regOutInput\" />&nbsp;&nbsp;<input\r\n");
	XYBody.Append("                                    type=\"checkbox\" id=\"getphone\" onclick=\"phone();\" name=\"getphone\" />同上\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\">\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">手机：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"mobile\" type=\"text\" id=\"mobile\" maxlength=\"11\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"TelMsg\" class=\"regOutTip\" style=\"margin-top: 25px;\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">所在部门：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"section\" type=\"text\" id=\"section\" maxlength=\"20\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"FaxMsg\" class=\"regOutTip\" style=\"margin-top: 25px;\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">您的职位：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"post\" type=\"text\" id=\"post\" maxlength=\"20\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">所在地区：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"divArea\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                                <input type=\"hidden\" id=\"areaid\" name=\"areaid\" />\r\n");
	XYBody.Append("                                <script type=\"text/javascript\">\r\n");
	XYBody.Append("                    var cla = new ClassType(\"cla\",'area','divArea','areaid');\r\n");
	XYBody.Append("                    cla.Mode =\"select\";\r\n");
	XYBody.Append("                    cla.Init();\r\n");
	XYBody.Append("                                </" + "script>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">邮编：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"zipcode\" maxlength=\"6\" type=\"text\" name=\"zipcode\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">联系地址：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"address\" type=\"text\" id=\"address\" maxlength=\"60\" size=\"50\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">公司网址：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"homepage\" maxlength=\"100\" type=\"text\" name=\"homepage\" size=\"50\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");

	if (isenabledim==true)
	{

	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">");	XYBody.Append(imtoolname.ToString());	XYBody.Append("：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"im\" maxlength=\"30\" size=\"30\" type=\"text\" name=\"im\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");

	}	//end if

	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td height=\"26\" align=\"right\" style=\"border-bottom: 1px solid #ccc;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">公司名称和主营业务</strong>&nbsp;&nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"6\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td width=\"130\" align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">贵公司名称：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td width=\"293\">\r\n");
	XYBody.Append("                                <input name=\"enterprisename\" type=\"text\" id=\"enterprisename\" maxlength=\"90\" size=\"50\"\r\n");
	XYBody.Append("                                    class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                注：无商号的个体经营者填写执照上的姓名，并标注个体经营。如张三（个体经营）。\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">企业性质：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\">\r\n");
	XYBody.Append("                                <input name=\"character\" type=\"radio\" value=\"企业单位\" checked=\"checked\" />企业单位\r\n");
	XYBody.Append("                                <input name=\"character\" type=\"radio\" value=\"个体经营\" />个体经营\r\n");
	XYBody.Append("                                <input name=\"character\" type=\"radio\" value=\"事业单位或社会团体\" />事业单位或社会团体\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\">\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">企业类别：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"classTypecompany\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                                <input type=\"hidden\" id=\"typeid\" name=\"typeid\" />\r\n");
	XYBody.Append("                                <script type=\"text/javascript\">\r\n");
	XYBody.Append("                        var clacompany = new ClassType(\"clacompany\",'company','classTypecompany','typeid');\r\n");
	XYBody.Append("                        clacompany.Mode =\"select\";\r\n");
	XYBody.Append("                        clacompany.Init();\r\n");
	XYBody.Append("                                </" + "script>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">主营方向：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"supply\" type=\"radio\" checked=\"checked\" name=\"way\" />\r\n");
	XYBody.Append("                                供方\r\n");
	XYBody.Append("                                <input id=\"buy\" type=\"radio\" name=\"way\" />\r\n");
	XYBody.Append("                                求方\r\n");
	XYBody.Append("                                <input id=\"both\" type=\"radio\" name=\"way\" />两者都有\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\" style=\"padding-top: 12px;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">经营模式：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\">\r\n");

	int md__loop__id=0;
	foreach(DataRow md in modelist.Rows)
	{
		md__loop__id++;

	XYBody.Append("                                <input type=\"checkbox\" value=\"" + md["M_Type"].ToString().Trim() + "\" name=\"bussinessmode\" />" + md["M_Type"].ToString().Trim() + "\r\n");

	}	//end loop

	XYBody.Append("                                <br />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td valign=\"top\" class=\"regOutTip\">\r\n");
	XYBody.Append("                                最多只能选择两种经营模式。\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">注册资本：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <select id=\"moneytype\" style=\"width: 97px\" name=\"moneytype\">\r\n");
	XYBody.Append("                                    <option value=\"人民币\">人民币</option>\r\n");
	XYBody.Append("                                </select>\r\n");
	XYBody.Append("                                <input id=\"regcapital\" type=\"text\" name=\"regcapital\" maxlength=\"20\" style=\"width: 83px\"\r\n");
	XYBody.Append("                                    class=\"regOutInput\" />万\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">公司成立年份：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"foundyear\" type=\"text\" name=\"foundyear\" size=\"15\" maxlength=\"4\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                成立年份，如2005\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">公司注册地：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"divRegArea\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                                <input type=\"hidden\" id=\"regareaid\" name=\"regareaid\" />\r\n");
	XYBody.Append("                                <script type=\"text/javascript\">\r\n");
	XYBody.Append("                    var cla1 = new ClassType(\"cla1\",'area','divRegArea','regareaid');\r\n");
	XYBody.Append("                    cla1.Mode =\"select\";\r\n");
	XYBody.Append("                    cla1.Init();\r\n");
	XYBody.Append("                                </" + "script>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">主要经营地点：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"operateaddress\" type=\"text\" id=\"operateaddress\" maxlength=\"100\" size=\"50\"\r\n");
	XYBody.Append("                                    class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                请填写业务部门所在主要地区\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">公司人数：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <select name=\"employeenumber\">\r\n");
	XYBody.Append("                                    <option value=\"50以下\">50以下</option>\r\n");
	XYBody.Append("                                    <option value=\"50 ~ 100\">50 ~ 100</option>\r\n");
	XYBody.Append("                                    <option value=\"100 ~ 200\">100 ~ 200</option>\r\n");
	XYBody.Append("                                    <option value=\"200以上\">200以上</option>\r\n");
	XYBody.Append("                                </select>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">供应产品和服务：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <textarea name=\"supplyproduct\" rows=\"2\" cols=\"50\" class=\"regOutInput\"></textarea>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                多个用“,”号隔开\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">需求产品和服务：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <textarea name=\"buyproduct\" rows=\"2\" cols=\"50\" class=\"regOutInput\"></textarea>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\" valign=\"top\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">简介：</strong>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <textarea id=\"synopsis\" cols=\"50\" rows=\"8\" name=\"synopsis\" class=\"regOutInput\"></textarea><br />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td class=\"regOutTip\">\r\n");
	XYBody.Append("                                · 请用中文详细说明贵公司的成立的历史,主营产品, 品牌,服务等优势。<br />\r\n");
	XYBody.Append("                                · 如果内容过于简单或填写单纯的产品介绍，将有可能无法通过审核。<br />\r\n");
	XYBody.Append("                                · 联系方式（电话，传真，手机，电子邮件等）请在会员资料中填写，此处请勿重复填写。\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"agreement\" type=\"checkbox\" value=\"on\" checked=\"checked\" id=\"Checkbox3\"\r\n");
	XYBody.Append("                                    onclick=\"isAgreement(this);\" />我同意各项服务条款&nbsp;&nbsp;<a target=\"_blank\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("agreement.htm\">点此阅读</a>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"btnInfoSubmit\" type=\"button\" value=\" 确定\" onclick=\"return FullModelRegUser();\" />&nbsp;&nbsp;\r\n");
	XYBody.Append("                                <input name=\"\" type=\"reset\" value=\" 取消 \" id=\"Reset2\" onclick=\"window.location.href='");	XYBody.Append(config.WebURL);	XYBody.Append("index.");	XYBody.Append(config.Suffix);	XYBody.Append("'\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <!-- 公司详细注册结束 -->\r\n");
	XYBody.Append("                <!-- 个人详细注册开始 -->\r\n");
	XYBody.Append("                <div id=\"person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td height=\"26\" align=\"right\" style=\"border-bottom: 1px solid #ccc;\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">个人详细信息</strong>&nbsp;&nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                &nbsp;\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                    <table width=\"880\" border=\"0\" align=\"center\" cellpadding=\"6\" cellspacing=\"0\">\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">真实姓名：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"i_realname\" type=\"text\" id=\"i_realname\" maxlength=\"20\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">性别：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"i_sex\" type=\"radio\" value=\"1\" checked />先生\r\n");
	XYBody.Append("                                <input name=\"i_sex\" type=\"radio\" value=\"0\" />女士\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">身份证号：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"i_idcard\" type=\"text\" id=\"i_idcard\" maxlength=\"18\" size=\"20\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">联系电话：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input maxlength=\"50\" name=\"i_telephone\" size=\"50\" type=\"text\" class=\"regOutInput\" /><br />\r\n");
	XYBody.Append("                                多个之间用,号隔开,格式：010-88888888-86 或 010-88888888\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">手机：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"i_mobile\" type=\"text\" id=\"i_mobile\" maxlength=\"11\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">所在地区：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <div id=\"divPArea\">\r\n");
	XYBody.Append("                                </div>\r\n");
	XYBody.Append("                                <input type=\"hidden\" id=\"pAreaId\" name=\"i_areaid\" />\r\n");
	XYBody.Append("                                <script type=\"text/javascript\">\r\n");
	XYBody.Append("                        var cla2 = new ClassType(\"cla2\",'area','divPArea','i_areaid');\r\n");
	XYBody.Append("                        cla2.Mode =\"select\";\r\n");
	XYBody.Append("                        cla2.Init();\r\n");
	XYBody.Append("                                </" + "script>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">邮编：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"i_zipcode\" maxlength=\"6\" type=\"text\" name=\"i_zipcode\" size=\"15\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                                <strong class=\"Font14_1\">联系地址：\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"i_address\" type=\"text\" id=\"i_address\" maxlength=\"60\" size=\"50\" class=\"regOutInput\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input name=\"agreement\" type=\"checkbox\" value=\"on\" checked=\"checked\" id=\"Checkbox2\"\r\n");
	XYBody.Append("                                    onclick=\"isAgreement(this);\" />我同意各项服务条款&nbsp;&nbsp;<a target=\"_blank\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("agreement.htm\">点此阅读</a>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                        <tr>\r\n");
	XYBody.Append("                            <td align=\"right\">\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                                <input id=\"btnPersonSubmit\" type=\"button\" value=\" 确定\" onclick=\"return FullModelRegIndividual();\" />&nbsp;&nbsp;\r\n");
	XYBody.Append("                                <input name=\"\" type=\"reset\" value=\" 取消 \" id=\"Reset3\" onclick=\"window.location.href='");	XYBody.Append(config.WebURL);	XYBody.Append("index.");	XYBody.Append(config.Suffix);	XYBody.Append("'\" />\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                            <td>\r\n");
	XYBody.Append("                            </td>\r\n");
	XYBody.Append("                        </tr>\r\n");
	XYBody.Append("                    </table>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <!-- 个人详细注册结束 -->\r\n");

	}	//end if

	XYBody.Append("            </div>\r\n");
	XYBody.Append("            </form>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("    </div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
