<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.search.advanced_search,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\" >\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("	<title> 高级搜索 - ");	XYBody.Append(config.webname);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"xyecom\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/xylib.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/search.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/search.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("	<script language =\"javascript\" type=\"text/javascript\"  src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/date.js\"></" + "script>\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");


	XYBody.Append("    <div id=\"s_body\">\r\n");
	XYBody.Append("    <ul class=\"s_comment\">\r\n");
	XYBody.Append("        <li class=\"choiceon\" id=\"tab1\"><a href=\"javascript:;\" onclick=\"selectSearchBox(1)\">产品搜索</a></li>\r\n");
	XYBody.Append("        <li class=\"choiceout\" id=\"tab2\"><a href=\"javascript:;\" onclick=\"selectSearchBox(2)\">加工搜索</a></li>\r\n");
	XYBody.Append("        <li class=\"choiceout\" id=\"tab3\"><a href=\"javascript:;\" onclick=\"selectSearchBox(3)\">招商代理搜索</a></li>\r\n");
	XYBody.Append("        <li class=\"choiceout\" id=\"tab4\"><a href=\"javascript:;\" onclick=\"selectSearchBox(4)\">服务搜索</a></li>\r\n");
	XYBody.Append("        <li class=\"choiceout\" id=\"tab5\"><a href=\"javascript:;\" onclick=\"selectSearchBox(5)\">企业搜索</a></li>\r\n");
	XYBody.Append("        <li class=\"choiceout\" id=\"tab6\"><a href=\"javascript:;\" onclick=\"selectSearchBox(6)\">资讯搜索</a></li>\r\n");
	XYBody.Append("    </ul>\r\n");
	XYBody.Append("   <!--供求搜索-->\r\n");
	XYBody.Append("   <div id=\"contentBox1\" style=\"display: block;\">\r\n");
	XYBody.Append("   <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("        <th>信息类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"offerInfoType\" value=\"sell\" checked=\"checked\" />供应\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"offerInfoType\" value=\"buy\" />求购\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"offerkey\" name=\"offerkey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>产品类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"supply\" style=\"display:block;\" ></div>\r\n");
	XYBody.Append("            <input id=\"offerTypeId\" runat=\"server\" type=\"hidden\" value=\"\" />\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla = new ClassType(\"cla\",'offer','supply','offerTypeId');\r\n");
	XYBody.Append("            cla.Mode =\"select\";\r\n");
	XYBody.Append("            cla.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>地区：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"areaByOffer\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"areaIdByOffer\"  name=\"areaIdByOffer\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla1 = new ClassType(\"cla1\",'area','areaByOffer','areaIdByOffer',2);\r\n");
	XYBody.Append("            cla1.Mode =\"select\";\r\n");
	XYBody.Append("            cla1.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>时间：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"0\" checked/>全部\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"1\" />今天\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"3\" />3天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"7\" />7天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"15\" />15天之内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByOffer\" value=\"30\" />30天之内\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnOfferSearch\" class=\"s_btn\" onclick=\"OfferSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div> \r\n");
	XYBody.Append("    <!--加工搜索-->\r\n");
	XYBody.Append("    <div id=\"contentBox2\" style=\"display: none;\">\r\n");
	XYBody.Append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("        <th>信息类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"machiningInfoType\" value=\"sell\" checked=\"checked\" />加工信息\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"machiningInfoType\" value=\"buy\" />寻求加工\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"machiningkey\" name=\"machiningkey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>加工类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"divMachining\" style=\"display:block;\" ></div>\r\n");
	XYBody.Append("            <input id=\"machiningTypeId\" runat=\"server\" type=\"hidden\" value=\"\" />\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("                var cla2 = new ClassType(\"cla2\", 'ventureType', 'divMachining', 'machiningTypeId');\r\n");
	XYBody.Append("            cla2.Mode =\"select\";\r\n");
	XYBody.Append("            cla2.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>地区：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"areaByMachining\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"areaIdByMachining\"  name=\"areaIdByMachining\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla3 = new ClassType(\"cla3\",'area','areaByMachining','areaIdByMachining',2);\r\n");
	XYBody.Append("            cla3.Mode =\"select\";\r\n");
	XYBody.Append("            cla3.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>时间：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"0\" checked/>全部\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"1\" />今天\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"3\" />3天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"7\" />7天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"15\" />15天之内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByMachining\" value=\"30\" />30天之内\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnMachiningSearch\" class=\"s_btn\" onclick=\"MachiningSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div> \r\n");
	XYBody.Append("    <!--招商搜索-->\r\n");
	XYBody.Append("    <div id=\"contentBox3\" style=\"display: none;\">\r\n");
	XYBody.Append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("        <th>信息类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"investmentInfoType\" value=\"sell\" checked=\"checked\" />诚招代理\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"investmentInfoType\" value=\"buy\" />代理企业\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"investmentkey\" name=\"investmentkey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>招商类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"divInvestment\" style=\"display:block;\" ></div>\r\n");
	XYBody.Append("            <input id=\"investmentTypeId\" runat=\"server\" type=\"hidden\" value=\"\" />\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla4 = new ClassType(\"cla4\",'investment','divInvestment','investmentTypeId');\r\n");
	XYBody.Append("            cla4.Mode =\"select\";\r\n");
	XYBody.Append("            cla4.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>地区：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"areaByInvestment\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"areaIdByInvestment\"  name=\"areaIdByInvestment\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla5 = new ClassType(\"cla5\",'area','areaByInvestment','areaIdByInvestment',2);\r\n");
	XYBody.Append("            cla5.Mode =\"select\";\r\n");
	XYBody.Append("            cla5.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>时间：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"0\" checked/>全部\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"1\" />今天\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"3\" />3天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"7\" />7天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"15\" />15天之内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByInvestment\" value=\"30\" />30天之内\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnInvestmentSearch\" class=\"s_btn\" onclick=\"InvestmentSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div> \r\n");
	XYBody.Append("    <!--服务搜索-->\r\n");
	XYBody.Append("    <div id=\"contentBox4\" style=\"display: none;\">\r\n");
	XYBody.Append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("    <tr>\r\n");
	XYBody.Append("        <th>信息类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"serviceInfoType\" value=\"sell\" checked=\"checked\" />服务信息\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"serviceInfoType\" value=\"buy\" />寻求服务\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"servicekey\" name=\"servicekey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>服务类型：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"divService\" style=\"display:block;\" ></div>\r\n");
	XYBody.Append("            <input id=\"serviceTypeId\" runat=\"server\" type=\"hidden\" value=\"\" />\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla6 = new ClassType(\"cla6\",'service','divService','serviceTypeId');\r\n");
	XYBody.Append("            cla6.Mode =\"select\";\r\n");
	XYBody.Append("            cla6.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>地区：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"areaByService\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"areaIdByService\"  name=\"areaIdByService\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla7 = new ClassType(\"cla7\",'area','areaByService','areaIdByService',2);\r\n");
	XYBody.Append("            cla7.Mode =\"select\";\r\n");
	XYBody.Append("            cla7.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>时间：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"0\" checked/>全部\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"1\" />今天\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"3\" />3天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"7\" />7天内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"15\" />15天之内\r\n");
	XYBody.Append("            <input type=\"radio\" name=\"dateByService\" value=\"30\" />30天之内\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnServiceSearch\" class=\"s_btn\" onclick=\"ServiceSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <!--企业搜索-->\r\n");
	XYBody.Append("    <div id=\"contentBox5\" style=\"display: none;\">\r\n");
	XYBody.Append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"userkey\" name=\"userkey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>企业分类：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"classTypecompany\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"userTypeId\"  name=\"userTypeId\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var clacompany = new ClassType(\"clacompany\",'company','classTypecompany','userTypeId');\r\n");
	XYBody.Append("            clacompany.Mode =\"select\";\r\n");
	XYBody.Append("            clacompany.Init();\r\n");
	XYBody.Append("            </" + "script>           \r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>地区：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"areaByUser\"></div>\r\n");
	XYBody.Append("            <input type =\"hidden\" id=\"areaIdByUser\"  name=\"areaIdByUser\"/>\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla8 = new ClassType(\"cla8\",'area','areaByUser','areaIdByUser',2);\r\n");
	XYBody.Append("            cla8.Mode =\"select\";\r\n");
	XYBody.Append("            cla8.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnUserSearch\" class=\"s_btn\" onclick=\"UserSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <!--资讯搜索-->\r\n");
	XYBody.Append("    <div id=\"contentBox6\" style=\"display: none;\">\r\n");
	XYBody.Append("    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"tabBody\">\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>关键字：</th>\r\n");
	XYBody.Append("        <td><input type=\"text\" id=\"newskey\" name=\"newskey\" value=\"\" size=\"40\" maxlength=\"40\" class=\"s_txt\"/></td>\r\n");
	XYBody.Append("      </tr>\r\n");
	XYBody.Append("      <tr>\r\n");
	XYBody.Append("        <th>资讯栏目：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            <div id=\"divNews\"></div>\r\n");
	XYBody.Append("            <input type=\"hidden\" id=\"newstitleid\" />\r\n");
	XYBody.Append("            <script type=\"text/javascript\">\r\n");
	XYBody.Append("            var cla9 = new ClassType(\"cla9\",'news','divNews','newstitleid');\r\n");
	XYBody.Append("            cla9.Mode =\"select\";\r\n");
	XYBody.Append("            cla9.Init();\r\n");
	XYBody.Append("            </" + "script>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("       </tr>\r\n");
	XYBody.Append("       <tr>\r\n");
	XYBody.Append("        <th>发布时间：</th>\r\n");
	XYBody.Append("        <td>\r\n");
	XYBody.Append("            从\r\n");
	XYBody.Append("            <input onclick=\"getDateString(this);\" id=\"newsStartDate\"  readonly=\"readonly\" name =\"newsStartDate\" class=\"s_txt s_date\" size=\"10\"/>\r\n");
	XYBody.Append("            至\r\n");
	XYBody.Append("            <input onclick=\"getDateString(this);\" id=\"newsEndDate\"  readonly=\"readonly\" name =\"newsEndDate\" class=\"s_txt s_date\" size=\"10\"/>\r\n");
	XYBody.Append("        </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th>资讯类型：</th>\r\n");
	XYBody.Append("            <td>\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"newsType\" value=\"\" checked=\"checked\"/>全部\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"newsType\" value=\"1\" />普通新闻\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"newsType\" value=\"2\" />图片新闻\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"newsType\" value=\"3\" />标题新闻\r\n");
	XYBody.Append("            </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th>是否推荐：</th>\r\n");
	XYBody.Append("            <td>\r\n");
	XYBody.Append("                 <input type=\"radio\" name=\"isCommend\" value=\"\" checked=\"checked\"/>全部\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"isCommend\" value=\"1\" />推荐\r\n");
	XYBody.Append("                <input type=\"radio\" name=\"isCommend\" value=\"0\" />不推荐      \r\n");
	XYBody.Append("            </td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("        <tr>\r\n");
	XYBody.Append("            <th></th>\r\n");
	XYBody.Append("            <td><input  type=\"button\" value =\" 搜索 \" id=\"btnNewsSearch\" class=\"s_btn\" onclick=\"AdvNewsSearch();\"/></td>\r\n");
	XYBody.Append("        </tr>\r\n");
	XYBody.Append("   </table>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append(" </div> \r\n");
	XYBody.Append("    <br />\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
