<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.baike.index,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\" id=\"html\">\r\n");
	XYBody.Append("<head>\r\n");


	if (pageinfo.PageError==1)
	{


	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");
	XYBody.Append("<title>消息提示</title>\r\n");
	XYBody.Append("");	XYBody.Append(pageinfo.Meta);	XYBody.Append("\r\n");
	XYBody.Append("<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("</head>\r\n");
	XYBody.Append("<body style=\"background-color:#f2f2f2\">\r\n");
	XYBody.Append("<div id=\"sysMsgbox\">\r\n");
	XYBody.Append("	<ul>\r\n");
	XYBody.Append("	    <li class=\"msg\">");	XYBody.Append(pageinfo.MsgboxText);	XYBody.Append("</li>\r\n");
	XYBody.Append("        <li><a href=\"");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("\">");	XYBody.Append(pageinfo.MsgboxURL);	XYBody.Append("</a></li>\r\n");
	XYBody.Append("         <li><a href=\"#\" onclick=\"history.back();\">返回继续操作</a></li>\r\n");
	XYBody.Append("        <li><a href=\"/\">返回首页</a> | <a href=\"#\" onclick=\"window.close();\">关闭本页</a></li>\r\n");
	XYBody.Append("    </ul>\r\n");
	XYBody.Append("    <div id=\"r_f\">2000-2009　" +  XYECOMCreateHTML("XY_Copyright").ToString() + "　版权所有　纵横易商软件</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");



	Response.Write(XYBody.ToString());
System.Web.HttpContext.Current.Response.End();
	

	}	//end if

	XYBody.Append("<title>");	XYBody.Append(seo.Title);	XYBody.Append("</title>\r\n");
	XYBody.Append("<meta name=\"description\" content=\"");	XYBody.Append(seo.Description);	XYBody.Append("\" />\r\n");
	XYBody.Append("<meta name=\"keywords\" content=\"");	XYBody.Append(seo.Keywords);	XYBody.Append("\" />\r\n");
	XYBody.Append("<meta name=\"robots\" content=\"all\" />\r\n");
	XYBody.Append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
	XYBody.Append("<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/XYLib.css\" type=\"text/css\"\r\n");
	XYBody.Append("    media=\"screen\" />\r\n");
	XYBody.Append("<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\"\r\n");
	XYBody.Append("    type=\"text/css\" />\r\n");
	XYBody.Append("<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/baike.css\" rel=\"stylesheet\"\r\n");
	XYBody.Append("    type=\"text/css\" />\r\n");
	XYBody.Append("<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\"\r\n");
	XYBody.Append("    language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/validate.js\"\r\n");
	XYBody.Append("    language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("<script language=\"javascript\" type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/UploadControl.js\"></" + "script>\r\n");


	XYBody.Append("</head>\r\n");
	XYBody.Append("<body onload=\"");	XYBody.Append(pageinfo.OnLoadEvents);	XYBody.Append("\">\r\n");
	XYBody.Append("<div id=\"wrap\">\r\n");
	XYBody.Append("<!--ad start -->\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");



	XYBody.Append("<div class=\"bk_search\">\r\n");
	XYBody.Append("    <div class=\"bk_sleft\">\r\n");
	XYBody.Append("        <!--<form class=\"bk_form\" action=\"");	XYBody.Append(config.WebURL);	XYBody.Append("baike/list.");	XYBody.Append(config.Suffix);	XYBody.Append("\" method=\"get\">\r\n");
	XYBody.Append("<font color=\"#0268cd\" size=\"2\"><b>百科搜索 </b></font> <input type=\"text\" name=\"keyword\" class=\"bk_input\">\r\n");
	XYBody.Append("<input type=\"submit\" value=\"搜索\" class=\"form3-input2\">\r\n");
	XYBody.Append("</form>-->\r\n");
	XYBody.Append("        <form class=\"form_search\">\r\n");
	XYBody.Append("        <span class=\"bk_bt\">百科搜索</span>\r\n");
	XYBody.Append("        <input type=\"hidden\" id=\"\" name=\"typeid\" />\r\n");
	XYBody.Append("        百科类别：<span id=\"classcatogry\"></span>\r\n");
	XYBody.Append("        <script type=\"text/javascript\">\r\n");
	XYBody.Append("			    var cla = new ClassType(\"cla\", 'baike', 'classcatogry', 'typeid',1);\r\n");
	XYBody.Append("                cla.Mode = \"select\";\r\n");
	XYBody.Append("                cla.Init();\r\n");
	XYBody.Append("        </" + "script>\r\n");
	XYBody.Append("        <input type=\"text\" class=\"inp\" id=\"txtkeyword\" />\r\n");
	XYBody.Append("        <input type=\"button\" class=\"submit2\" value=\"搜索\" onclick=\"BaikeListSearch()\" />\r\n");
	XYBody.Append("        </form>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"bk_sright\">\r\n");
	XYBody.Append("        <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("baike/lemmaadd.");	XYBody.Append(config.Suffix);	XYBody.Append("\">创建词条</a> <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("            用户注册</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");


	XYBody.Append("<div id=\"left\">\r\n");
	XYBody.Append("<div id=\"bkfl\" class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2\">百科分类</h2>\r\n");
	XYBody.Append("	<div class=\"bor-white-t\"></div>\r\n");
	XYBody.Append("	" +  XYECOMCreateHTML("XY_CLS_bk_class").ToString() + "\r\n");
	XYBody.Append("    	<dl>\r\n");
	XYBody.Append("	  <dt><a href=\"#\" >娱乐休闲</a></dt>\r\n");
	XYBody.Append("        		<dd class=\"link_gray\">\r\n");
	XYBody.Append("      		 	 <a href=\"#\" >电影视频</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >音乐</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >游戏</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >小说</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >门户论坛</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >星座</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >体育</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >军事</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >社区交友</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >新闻</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >图片</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >明星</a>\r\n");
	XYBody.Append("         		 </dd>\r\n");
	XYBody.Append("         	</dl>\r\n");
	XYBody.Append("    	<dl>\r\n");
	XYBody.Append("	  <dt><a href=\"#\" >地方网站</a></dt>\r\n");
	XYBody.Append("        		<dd class=\"link_gray\">\r\n");
	XYBody.Append("      		 	 <a href=\"#\" >北京</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >浙江</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >江苏</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >广东</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >广西</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >上海</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >湖南</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >湖北</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >山东</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >山西</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >天津</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >河南</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >河北</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >福建</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >安徽</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >重庆</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >四川</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >江西</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >贵州</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >云南</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >内蒙</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >宁夏</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >新疆</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >西藏</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >青海</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >台湾</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >香港</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >澳门</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >海南</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >甘肃</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >陕西</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >吉林</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >辽宁</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >黑龙江</a>\r\n");
	XYBody.Append("         		 </dd>\r\n");
	XYBody.Append("         	</dl>\r\n");
	XYBody.Append("    	<dl>\r\n");
	XYBody.Append("	  <dt><a href=\"#\" >电脑网络</a></dt>\r\n");
	XYBody.Append("        		<dd class=\"link_gray\">\r\n");
	XYBody.Append("      		 	 <a href=\"#\" >个人博客</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >邮件网盘</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >软件下载</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >域名空间</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >开源代码</a>\r\n");
	XYBody.Append("         	 	 <a href=\"#\" >导航链接</a>\r\n");
	XYBody.Append("         		 </dd>\r\n");
	XYBody.Append("         	</dl>\r\n");
	XYBody.Append("    	<dl>\r\n");
	XYBody.Append("	  <dt><a href=\"#\" >其他分类</a></dt>\r\n");
	XYBody.Append("        	</dl>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("<div id=\"zxpl\" class=\"columns\">\r\n");
	XYBody.Append("   <h2 class=\"col-h2\">最近评论</h2>\r\n");
	XYBody.Append("   <ul class=\"col-ul a-c mar-t8\">\r\n");
	XYBody.Append("      </ul>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div id=\"mid\">\r\n");
	XYBody.Append("<div id=\"tjct\"  class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2 link_black\"><span class=\"l\">推荐词条</span><a href=\"#\"  class=\"r font12\">更多&gt;&gt;</a></h2>\r\n");
	XYBody.Append("		" +  XYECOMCreateHTML("XY_Wikipediaindex").ToString() + "\r\n");
	XYBody.Append("	<div id=\"other-word\">\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("<!--ad start -->\r\n");
	XYBody.Append("<!--ad end -->\r\n");
	XYBody.Append("<div id=\"zjgx\" class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2 link_black\"><span class=\"l til-fl\">最近更新</span><a href=\"#\"  class=\"r font12\">更多&gt;&gt;</a></h2>\r\n");
	XYBody.Append("   <ul class=\"col-ul a-c\">\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[电影视频] </a><a href=\"#\"  class=\"ctm\" title=\"\">奇艺网</a><a href=\"#\"  class=\"name\">admin</a><span class=\"r\">创建于 04-22 22:25 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[社区交友] </a><a href=\"#\"  class=\"ctm\" title=\"\">淘男网</a><a href=\"#\"  class=\"name\">admin</a><span class=\"r\">创建于 03-25 09:14 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[电脑网络] </a><a href=\"#\"  class=\"ctm\" title=\"\">35互联</a><a href=\"#\"  class=\"name\">admin</a><span class=\"r\">创建于 03-17 20:22 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[湖南] </a><a href=\"#\"  class=\"ctm\" title=\"\">湘潭人才网</a><a href=\"#\"  class=\"name\">czj88888</a><span class=\"r\">创建于 02-24 20:36 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[湖南] </a><a href=\"#\"  class=\"ctm\" title=\"\">株洲人才网</a><a href=\"#\"  class=\"name\">czj88888</a><span class=\"r\">创建于 02-24 12:18 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[湖南] </a><a href=\"#\"  class=\"ctm\" title=\"\">湖南人才网</a><a href=\"#\"  class=\"name\">czj88888</a><span class=\"r\">创建于 02-24 12:15 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[大学教育] </a><a href=\"#\"  class=\"ctm\" title=\"\">外航投资移民</a><a href=\"#\"  class=\"name\">aa282668989</a><span class=\"r\">创建于 02-23 13:30 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[个人博客] </a><a href=\"#\"  class=\"ctm\" title=\"\">嘀咕网</a><a href=\"#\"  class=\"name\">微博</a><span class=\"r\">编辑于 02-03 22:00 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[小说] </a><a href=\"#\"  class=\"ctm\" title=\"\">逐浪小说网</a><a href=\"#\"  class=\"name\">小说爱好者</a><span class=\"r\">创建于 01-30 16:50 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[导航链接] </a><a href=\"#\"  class=\"ctm\" title=\"\">265导航网址之家</a><a href=\"#\"  class=\"name\">admin</a><span class=\"r\">编辑于 01-30 16:16 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[小说] </a><a href=\"#\"  class=\"ctm\" title=\"\">起点中文网</a><a href=\"#\"  class=\"name\">小说爱好者</a><span class=\"r\">创建于 01-29 22:49 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[电脑网络] </a><a href=\"#\"  class=\"ctm\" title=\"\">中介网</a><a href=\"#\"  class=\"name\">中介网</a><span class=\"r\">创建于 01-29 15:07 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[软件下载] </a><a href=\"#\"  class=\"ctm\" title=\"\">丁香鱼工作室</a><a href=\"#\"  class=\"name\">好人</a><span class=\"r\">编辑于 01-29 11:03 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[网上购物] </a><a href=\"#\"  class=\"ctm\" title=\"\">买麦网</a><a href=\"#\"  class=\"name\">好人</a><span class=\"r\">创建于 01-25 14:54 </span></li>\r\n");
	XYBody.Append("         		<li><a href=\"#\"  class=\"l til-fl\">[其他分类] </a><a href=\"#\"  class=\"ctm\" title=\"\">Technorati</a><a href=\"#\"  class=\"name\">好人</a><span class=\"r\">创建于 01-25 14:27 </span></li>		\r\n");
	XYBody.Append("      </ul>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div id=\"right\" class=\"default-r\">\r\n");
	XYBody.Append("<div id=\"notice\" class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2 link_black\"><span class=\"l\">站内公告</span></h2>\r\n");
	XYBody.Append("	<p class=\"mar-lr8 mar-t8\">本站是由<span style=\"color:#FF0000\">1</span>位网民共同撰写的百科全书，目前已收录词条<span style=\"color:#FF0000\"> 0</span>个</p>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div id=\"yzwkb\" class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2 link_black\"><span class=\"l\">排行榜</span></h2>\r\n");
	XYBody.Append("	<ul id=\"topuser\" class=\"col-ul a-c \">\r\n");
	XYBody.Append("				<li><span class=\"ranking\">1</span><a href=\"#\" class=\"l\" target=\"_blank\">admin</a> <span class=\"r1\">91</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">2</span><a href=\"#\" class=\"l\" target=\"_blank\">好人</a> <span class=\"r1\">50</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">3</span><a href=\"#\" class=\"l\" target=\"_blank\">czj88888</a> <span class=\"r1\">36</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">4</span><a href=\"#\" class=\"l\" target=\"_blank\">小说爱好者</a> <span class=\"r1\">30</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">5</span><a href=\"#\" class=\"l\" target=\"_blank\">aa282668989</a> <span class=\"r1\">25</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">6</span><a href=\"#\" class=\"l\" target=\"_blank\">微博</a> <span class=\"r1\">25</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">7</span><a href=\"#\" class=\"l\" target=\"_blank\">中介网</a> <span class=\"r1\">25</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">8</span><a href=\"#\" class=\"l\" target=\"_blank\">danglijie</a> <span class=\"r1\">20</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">9</span><a href=\"#\" class=\"l\" target=\"_blank\">bcgzll</a> <span class=\"r1\">20</span></li>\r\n");
	XYBody.Append("				<li><span class=\"ranking\">10</span><a href=\"#\" class=\"l\" target=\"_blank\">fm234</a> <span class=\"r1\">20</span></li>\r\n");
	XYBody.Append("				<li><a href=\"#\" class=\"r bg_no\">更多&gt;&gt;</a></li>\r\n");
	XYBody.Append("	</ul>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div id=\"rmbq\" class=\"columns\">\r\n");
	XYBody.Append("	<h2 class=\"col-h2 link_black\"><span class=\"l\">热门标签</span></h2>\r\n");
	XYBody.Append("	<ul class=\"col-ul a-c\">\r\n");
	XYBody.Append("    	</ul>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clear\"></div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
