<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.news.index,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");

	XYBody.Append("	<title>");	XYBody.Append(seo.Title);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"");	XYBody.Append(seo.Description);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"");	XYBody.Append(seo.Keywords);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"/>\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=\"gb2312\" />\r\n");
	XYBody.Append("	<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/XYLib.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/channel.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/news.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>	\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/validate.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/news.js\" language=\"javascript\"></" + "script>\r\n");


	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");




	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");








	XYBody.Append("	<div id=\"news_cnt1\">\r\n");
	XYBody.Append("		<div id=\"left\">\r\n");
	XYBody.Append("			<div id=\"cntA\">\r\n");
	XYBody.Append("				<div id=\"news_slide\">" +  XYECOMCreateHTML("XY_SlideTop5ByNewsIndex").ToString() + " </div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("					<h2 id=\"x_tab1\" class=\"\" class=\"selected\" onmouseover=\"xy_selectBox(2,1,'x','selected');\"><a target=\"_blank\" href=\"#\">人物访谈</a></h2>\r\n");
	XYBody.Append("			        <h2 id=\"x_tab2\"  onmouseout=\"xy_selectBox(2,2,'x','selected');\"><a target=\"_blank\" href=\"#\">科研技术</a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"x_box1\" class=\"Mblk_01\"  >\r\n");
	XYBody.Append("					<div class=\"pictext\">\r\n");
	XYBody.Append("						<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("						<div id=\"rt\">\r\n");
	XYBody.Append("							<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("							<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"com_pages\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_NewsIndex_RenWuZhuanFang").ToString() + "\r\n");
	XYBody.Append("					    </ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"x_box2\" class=\"Mblk_01\" style=\"display:none\">\r\n");
	XYBody.Append("					<div class=\"pictext\">\r\n");
	XYBody.Append("						<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("						<div id=\"rt\">\r\n");
	XYBody.Append("							<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("							<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"com_pages\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_NewsIndex_KeYanJIshu").ToString() + "\r\n");
	XYBody.Append("					    </ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"cntB\">\r\n");
	XYBody.Append("				<div id=\"news_headline\">\r\n");
	XYBody.Append("					<div class=\"tit\"><span class=\"fright\"><a href=\"\">更多></a></span><h2>要闻</h2></div>\r\n");
	XYBody.Append("					<div class=\"main\">\r\n");
	XYBody.Append("						<h3><a href=\"#\">Palm Pre评测二:webOS系统揭秘</a></h3>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							 " +  XYECOMCreateHTML("XY_Index_TuiJianNews").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"MTitle_01\">\r\n");
	XYBody.Append("					<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>业界资讯</strong></a></h2>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"con01\" class=\"Mblk_01 newsmid\">\r\n");
	XYBody.Append("					<div class=\"com_pages2\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_YeJieZIXun").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"clr\"></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"y_tab1\" class=\"\" onmouseover=\"xy_selectBox(2,1,'y','selected');\"><a target=\"_blank\" href=\"#\">名优企业</a></h2>\r\n");
	XYBody.Append("			    <h2 id=\"y_tab2\" class=\"selected\" onmouseover=\"xy_selectBox(2,2,'y','selected');\"><a target=\"_blank\" href=\"#\">最新企业</a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"y_box1\" class=\"Mblk_01\"  style=\"display:none\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_MingYouQiYe").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("					<div class=\"rank_pic\">\r\n");
	XYBody.Append("						<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_11.gif\" width=\"238\" height=\"50\" alt=\"\" /></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer\" style=\"height:7px;\"></div>\r\n");
	XYBody.Append("            <div id=\"y_box2\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_ZuiXinQiYe").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("					<div class=\"rank_pic\">\r\n");
	XYBody.Append("						<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_11.gif\" width=\"238\" height=\"50\" alt=\"\" /></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"z_tab1\" class=\"\" onmouseover=\"xy_selectBox(2,1,'z','selected');\"><a target=\"_blank\" href=\"#\">名优企业</a></h2>\r\n");
	XYBody.Append("			    <h2 id=\"z_tab2\"  class=\"selected\" onmouseover=\"xy_selectBox(2,2,'z','selected');\"><a target=\"_blank\" href=\"#\">最新企业</a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"z_box1\"  style=\"display:none\" class=\"Mblk_01 newsright\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_ZuiXinQiYe").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"z_box2\" class=\"Mblk_01 newsright\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_MingYouQiYe").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div class=\"bnr\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_3.gif\" width=\"980\" height=\"74\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("	<div id=\"news_cnt2\">\r\n");
	XYBody.Append("		<div id=\"left\">\r\n");
	XYBody.Append("			<div class=\"area1\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_image\"><h2>企业大全</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt padding15\" style=\"width:695px;\">\r\n");
	XYBody.Append("					" +  XYECOMCreateHTML("XY_NewsIndex_TuPianXinWentop").ToString() + "\r\n");
	XYBody.Append("					<div id=\"main\">\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_NewsIndex_TuPianXinWen6").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer height8\"></div>\r\n");
	XYBody.Append("			<div class=\"news_lists\">\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<div class=\"MTitle_01\">\r\n");
	XYBody.Append("						<h2 id=\"h201\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>本站动态</strong></a></h2>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("						<div class=\"pictext\">\r\n");
	XYBody.Append("							<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("							<div id=\"rt\">\r\n");
	XYBody.Append("								<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("								<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("							</div>\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"com_pages2\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								 " +  XYECOMCreateHTML("XY_NewsIndex_BenZhanDongTaiF4").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<div class=\"MTitle_01\">\r\n");
	XYBody.Append("						<h2 id=\"h201\" class=\"\"><a target=\"_blank\" class=\"big\" href=\"#\"><strong>业界资讯</strong></a></h2>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("						<div class=\"pictext\">\r\n");
	XYBody.Append("							<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("							<div id=\"rt\">\r\n");
	XYBody.Append("								<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("								<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("							</div>\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"com_pages2\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								 " +  XYECOMCreateHTML("XY_NewsIndex_YeJieZiXunF4").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"clr spacer height8\"></div>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<div class=\"MTitle_01\">\r\n");
	XYBody.Append("						<span class=\"fright\">更多</span><h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>企业动态</strong></a></h2>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div id=\"con01\" class=\"Mblk_01\" style=\"border-bottom:0;\">\r\n");
	XYBody.Append("						<div class=\"pictext\">\r\n");
	XYBody.Append("							<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("							<div id=\"rt\">\r\n");
	XYBody.Append("								<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("								<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("							</div>\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"com_pages2\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								 " +  XYECOMCreateHTML("XY_NewsIndex_QiYeDongTaiF4").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<div class=\"MTitle_01\">\r\n");
	XYBody.Append("						<span class=\"fright\">更多</span><h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>展会资讯</strong></a></h2>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div id=\"con01\" class=\"Mblk_01\" style=\"border-bottom:0;\">\r\n");
	XYBody.Append("						<div class=\"pictext\">\r\n");
	XYBody.Append("							<div id=\"lt\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_14.gif\" width=\"80\" height=\"60\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("							<div id=\"rt\">\r\n");
	XYBody.Append("								<h4><a href=\"\">江苏上海手机上网资费大跳水</a></h4>\r\n");
	XYBody.Append("								<p>中国对其拥有不可置疑的所有权，这些文物理应归还中国。拍卖战争中非法...</p>\r\n");
	XYBody.Append("							</div>\r\n");
	XYBody.Append("							<div class=\"clr\"></div>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"com_pages2\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								 " +  XYECOMCreateHTML("XY_NewsIndex_ZhanHuiZiXunF4").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<span class=\"fright\">更多</span><h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>业界资讯</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						 " +  XYECOMCreateHTML("XY_Index_YeJieZIXun").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer height8\"></div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<span class=\"fright\">更多</span><h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>业界资讯</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						 " +  XYECOMCreateHTML("XY_Index_YeJieZIXun").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer height8\"></div>\r\n");
	XYBody.Append("			<div class=\"news_exhi\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("					<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_1.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("					<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_2.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("					<li><a href=\"#\" ><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_meeting_3.gif\" alt='展会合作'></a></li>\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer height8\"></div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"h201\" class=\"\"><a target=\"_blank\" href=\"#\" class=\"big\"><strong>业界资讯</strong></a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"con01\" class=\"Mblk_01\" style=\"border-bottom:0;\">\r\n");
	XYBody.Append("				<div class=\"com_pages\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						 " +  XYECOMCreateHTML("XY_Index_YeJieZIXun").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"news_cnt2_btm\" class=\"spacer\"></div>\r\n");



	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
