<%@ Page language="c#" AutoEventWireup="false" EnableViewState="false" Inherits="XYECOM.Page.company.index,XYECOM.Page" %>
<%@ Import namespace="System.Data" %>
<%@ Import namespace="XYECOM.Core" %>
<%@ Import namespace="XYECOM.Model" %>
<%@ Import namespace="XYECOM.Business" %>
<%@ Import namespace="XYECOM.Template" %>
<%@ Import namespace="XYECOM.Configuration" %>
<script runat="server">
protected override void OnLoad(EventArgs e)
{
	base.OnLoad(e);
	XYBody.Append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
	XYBody.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
	XYBody.Append("<head>\r\n");

	XYBody.Append("	<title>");	XYBody.Append(seo.Title);	XYBody.Append("</title>\r\n");
	XYBody.Append("	<meta name=\"description\" content=\"");	XYBody.Append(seo.Description);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"keywords\" content=\"");	XYBody.Append(seo.Keywords);	XYBody.Append("\" />\r\n");
	XYBody.Append("	<meta name=\"robots\" content=\"all\"  />\r\n");
	XYBody.Append("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=\"gb2312\" />\r\n");
	XYBody.Append("	<link rel=\"stylesheet\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/css/XYLib.css\" type=\"text/css\" media=\"screen\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/global.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/channel.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<link href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/css/news.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("common/js/base.js\" language=\"javascript\"></" + "script>	\r\n");
	XYBody.Append("	<script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/login.js\" language=\"javascript\"></" + "script>\r\n");
	XYBody.Append("    <script type=\"text/javascript\" src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/js/validate.js\" language=\"javascript\"></" + "script>\r\n");


	XYBody.Append("</head>\r\n");
	XYBody.Append("<body>\r\n");
	XYBody.Append("<div id=\"wrapper\">\r\n");

	XYBody.Append("<div id=\"hd_info\">\r\n");
	XYBody.Append("    <div id=\"cnts\">\r\n");
	XYBody.Append("        <div id=\"site_cang\">\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_idx.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a href=\"#\" onclick=\"this.style.behavior='url(#default#homepage)';this.setHomePage('");	XYBody.Append(config.WebURL);	XYBody.Append("');\">\r\n");
	XYBody.Append("                设为首页</a>&nbsp;&nbsp;\r\n");
	XYBody.Append("            <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_cang.gif\" width=\"16\"\r\n");
	XYBody.Append("                height=\"16\" alt=\"\" align=\"absmiddle\" />\r\n");
	XYBody.Append("            <a style=\"cursor: hand\" onclick=\"window.external.addFavorite('");	XYBody.Append(config.WebURL);	XYBody.Append("','纵横易商软件')\">\r\n");
	XYBody.Append("                加为收藏</a>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"log_info\">\r\n");
	XYBody.Append("            <div id=\"login\">\r\n");
	XYBody.Append("                用户名：<input type=\"text\" class=\"com\" name=\"top_username\" id=\"top_username\" onkeydown=\"_xy_KeyNext('top_password');\" />\r\n");
	XYBody.Append("                密码：<input type=\"password\" name=\"top_password\" class=\"com\" id=\"top_password\" onkeydown=\"_xy_KeyPress('_btnTopLogin');\" />\r\n");

	if (config.IsEnabledVCode("login"))
	{

	XYBody.Append("                验证码： ");	XYBody.Append(pageinfo.GetValidateCodeHTML("top_vcode","top_vimg"));	XYBody.Append("\r\n");

	}	//end if

	XYBody.Append("                <input id=\"_btnTopLogin\" type=\"button\" class=\"top_login\" onclick=\"return xy_TopLogin();\" />\r\n");
	XYBody.Append("                &nbsp;&nbsp;<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("register.");	XYBody.Append(config.Suffix);	XYBody.Append("\">注册</a> | <a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("getPassword.");	XYBody.Append(config.Suffix);	XYBody.Append("\">\r\n");
	XYBody.Append("                    忘记密码</a> | <a href=\"##\">[VIP会员]</a> | <a href=\"##\">帮助中心</a>| <a style=\"color:Red\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("quickbuy.");	XYBody.Append(config.Suffix);	XYBody.Append("\">快速发布求购</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <span id=\"logined\" style=\"display: none;\">欢迎您，<font id=\"uname\"></font> | <a id=\"ucenter\">\r\n");
	XYBody.Append("            我的用户中心</a>| <a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("logout.");	XYBody.Append(config.suffix);	XYBody.Append("\">[退出]</a> <font id=\"logined_user\"\r\n");
	XYBody.Append("                style=\"display: none;\">企业用户相关内容</font> <font id=\"logined_person\" style=\"display: none;\">\r\n");
	XYBody.Append("                    个人用户相关内容</font> </span>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<script>    Login2();</" + "script>\r\n");



	XYBody.Append("<div id=\"header\">\r\n");
	XYBody.Append("    <div id=\"local_channel\">\r\n");
	XYBody.Append("        <span class=\"fright\"><a href=\"#\" onclick=\"div_opennew('_xy_div_allarea',200,100);return false;\">\r\n");
	XYBody.Append("            所有地区</a>\r\n");
	XYBody.Append("            <div id=\"_xy_div_allarea\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_allarea')\"\r\n");
	XYBody.Append("                onmouseout=\"div_mouseout('_xy_div_allarea');\">\r\n");
	XYBody.Append("                <a href=\"\">山东</a> <a href=\"\">四川</a> <a href=\"\">陕西</a> <a href=\"\">广东</a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </span><strong>地区频道：</strong>" +  XYECOMCreateHTML("XY_ASN_shandong").ToString() + " | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">\r\n");
	XYBody.Append("            河南农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">湖南农业网</a> | <a href=\"#\" class=\"waiting\"\r\n");
	XYBody.Append("                title=\"暂未开通\">沈阳农业网</a> | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">广东农业网</a>\r\n");
	XYBody.Append("        | <a href=\"#\" class=\"waiting\" title=\"暂未开通\">四川农业网</a>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div id=\"mains\">\r\n");
	XYBody.Append("        <div id=\"left\">\r\n");
	XYBody.Append("            <div id=\"logo\">\r\n");
	XYBody.Append("                <a href=\"/\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/logo.gif\" width=\"219\"\r\n");
	XYBody.Append("                        height=\"50\" alt=\"\" border=\"0\" /></a></div>\r\n");
	XYBody.Append("            <div id=\"site_tube\">\r\n");
	XYBody.Append("                [ &nbsp;&nbsp;<a href=\"\" class=\"orange\">中国农业网主站</a> &nbsp; <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\"\r\n");
	XYBody.Append("                    class=\"gray\">切换其它站点</a> <a href=\"#\" onclick=\"div_opennew('_xy_div_alltrade',200,100);return false;\">\r\n");
	XYBody.Append("                        <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_site_chg.gif\"\r\n");
	XYBody.Append("                            width=\"11\" height=\"11\" alt=\"\" align=\"absmiddle\" /></a>&nbsp;&nbsp; ]\r\n");
	XYBody.Append("                <div id=\"_xy_div_alltrade\" style=\"display: none\" onmouseover=\"div_mouseover('_xy_div_alltrade')\"\r\n");
	XYBody.Append("                    onmouseout=\"div_mouseout('_xy_div_alltrade');\">\r\n");
	XYBody.Append("                    <a href=\"\">分站1</a> <a href=\"\">分站2</a> <a href=\"\">分站3</a> <a href=\"\">分站4</a>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div id=\"right\">\r\n");
	XYBody.Append("            <div id=\"site_nav\">\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    行业频道</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("                <div class=\"c_name\">\r\n");
	XYBody.Append("                    新闻资讯</div>\r\n");
	XYBody.Append("                <div class=\"text\">\r\n");
	XYBody.Append("                    <ul>\r\n");
	XYBody.Append("                        <li><a href=\"\">天气</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">男人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">女人</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">新娘</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">母婴</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">健康</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">吃喝</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">旅游</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">出国</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">读书</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">教育</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">原创</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">财经</a></li>\r\n");
	XYBody.Append("                        <li><a href=\"\">留学</a></li>\r\n");
	XYBody.Append("                    </ul>\r\n");
	XYBody.Append("                </div>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("            <div id=\"hd_bnr\">\r\n");
	XYBody.Append("                <a href=\"\">\r\n");
	XYBody.Append("                    <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_bnr_1.gif\" width=\"163\"\r\n");
	XYBody.Append("                        height=\"76\" alt=\"\" /></a>\r\n");
	XYBody.Append("            </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("        <div class=\"clr\">\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("    <div class=\"clr\">\r\n");
	XYBody.Append("    </div>\r\n");
	XYBody.Append("</div>\r\n");
	XYBody.Append("<div class=\"clr\">\r\n");
	XYBody.Append("</div>\r\n");



	XYBody.Append("	<div class=\"search\">\r\n");
	XYBody.Append("		<div class=\"sh_tab\">\r\n");
	XYBody.Append("			<div class=\"order\">\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("keyword/\">订购固定排名</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<ul id=\"_xy_big_menu_box\">\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_index\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("\" class=\"tabactive\"><span>首 页</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_news\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("news/index.aspx\"><span>新闻资讯</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_offer\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("offer/index.aspx\"><span>产品中心</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_investment\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("investment/index.aspx\"><span>招商加盟</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_company\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("company/index.aspx\"><span>行业公司</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_job\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("job/index.aspx\"><span>人才招聘</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_brand\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("brand/index.aspx\"><span>行业品牌</span></a></li>				\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_exhibition\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("exhibition/index.aspx\"><span>展会信息</span></a></li>\r\n");
	XYBody.Append("				<li><a id=\"_xymenu_survey\" href=\"");	XYBody.Append(config.WebURL);	XYBody.Append("survey/index.aspx\"><span>调查问卷</span></a></li>\r\n");
	XYBody.Append("				<li style=\"display:none;\"><a href=\"#\"><span>社区交流</span></a></li>\r\n");
	XYBody.Append("				<div class=\"clr\"></div>\r\n");
	XYBody.Append("			</ul>\r\n");
	XYBody.Append("			<script type=\"text/javascript\">xy_Sel_CurBigMenu();</" + "script>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"sh_cnt\">\r\n");
	XYBody.Append("			<div id=\"main\">\r\n");
	XYBody.Append("				<input type=\"text\" id=\"txtsearchkey\" name=\"sch_text\" class=\"textsearch\" onkeydown=\"_xy_KeyPress('DoSearch');\"/>\r\n");
	XYBody.Append("				<div class=\"soSelect\" onclick=\"xy_ShowSearchMenu();\">\r\n");
	XYBody.Append("					<div class=\"option_current\" id=\"headSlected\" >产品</div>\r\n");
	XYBody.Append("					<div class=\"option_arrow\">\r\n");
	XYBody.Append("						<a href=\"#\"><span class=\"arrow\"></span></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("					<ul onmouseover=\"drop_mouseover('head')\" onmouseout=\"drop_mouseout('head');\" style=\"display: none;\" class=\"options\" id=\"headSel\">\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('产品','offer','sell');\">产品</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('求购','buy','buy');\">求购</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('招商','investment','sell');\">招商</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('加盟','investment','buy');\">加盟</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('融资','venture','sell');\">融资</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('服务','service','sell');\">服务</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('企业','company','sell');\">企业</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('资讯','news','');\">资讯</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('人才','job','');\">人才</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('品牌','brand','');\">品牌</a></li>\r\n");
	XYBody.Append("					    <li><a href=\"#\" onclick=\"xy_SelectSearchMenu('展会','exhibition','');\">展会</a></li>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_FlagName\" value=\"offer\"/>\r\n");
	XYBody.Append("				<input type=\"hidden\" id=\"xy_InfoType\" value=\"sell\"/>\r\n");
	XYBody.Append("				<button value=\"搜索\" id=\"DoSearch\" name=\"DoSearch\" class=\"btsearch\" onclick=\"xy_search();\"/>搜索</button>\r\n");
	XYBody.Append("				<a href=\"/search/advanced_search.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[高级搜索]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("contributor.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[投稿]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("post.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[发布信息]</a>\r\n");
	XYBody.Append("				<a href=\"");	XYBody.Append(config.weburl);	XYBody.Append("baike/index.");	XYBody.Append(config.Suffix);	XYBody.Append("\" class=\"black\">[百科]</a>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"sch_bnr\"><a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_5.jpg\" width=\"170\" height=\"77\" alt=\"\" /></a></div>\r\n");
	XYBody.Append("			<div id=\"hot_schs\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("					<li><strong>热门搜索词：</strong></li>\r\n");
	XYBody.Append("					<li>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_Index_ReMenSouSuoGuanjianzi").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</li>\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	</div>\r\n");


	XYBody.Append("	<div id=\"news_cnt1\" style=\"margin-bottom:6px;\">\r\n");
	XYBody.Append("		<div id=\"left\">\r\n");
	XYBody.Append("			<div class=\"area1\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_compy1\"><h2>热点资讯</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"info_lt\">\r\n");
	XYBody.Append("						<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_8.jpg\" width=\"220\" height=\"110\" alt=\"\" /></a>\r\n");
	XYBody.Append("						<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_CompanyIndex_GongSiZiXunLeft").ToString() + "\r\n");
	XYBody.Append("						</ul>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"info_rt\">\r\n");
	XYBody.Append("						<div class=\"Bm_1\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_CompanyIndex_GongSiZiXunRightIMG").ToString() + "\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"Bm_11\">\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_CompanyIndex_GongSiZiXuntop").ToString() + "\r\n");
	XYBody.Append("							<ul class=\"Bm_12 fia\">\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_CompanyIndex_GongSiZiXunCenter").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer\" style=\"height:6px;\"></div>\r\n");
	XYBody.Append("			<div class=\"area1\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_compy2\"><h2>按地区查找</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"mapkuang\">\r\n");
	XYBody.Append("						<div class=\"mapleft\">\r\n");
	XYBody.Append("							<img src=\"http://www.glass.cn/glass/company/chinaditu.gif\" width=\"350\" height=\"294\" border=\"0\" usemap=\"#Map\" />\r\n");
	XYBody.Append("							<map name=\"Map\" id=\"Map\">\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"47,90,85,108\" href=\"company_p32_a1032.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"233,97,266,112\" href=\"company_p1_a1001.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"280,37,331,52\" href=\"company_p10_a1010.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"266,115,300,129\" href=\"company_p2_a1002.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"285,167,318,182\" href=\"company_p3_a1003.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"174,186,207,201\" href=\"company_p4_a1004.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"231,113,264,128\" href=\"company_p5_a1005.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"209,129,242,144\" href=\"company_p6_a1006.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"293,222,325,237\" href=\"company_p7_a1007.html\" target=\"_blank\" />\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"267,91,301,106\" href=\"company_p8_a1008.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"286,69,318,84\" href=\"company_p9_a1009.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"259,148,292,163\" href=\"company_p11_a1011.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"276,186,309,201\" href=\"company_p12_a1012.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"249,166,282,181\" href=\"company_p13_a1013.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"256,205,289,220\" href=\"company_p14_a1014.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"241,187,274,202\" href=\"company_p15_a1015.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"247,129,280,144\" href=\"company_p16_a1016.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"223,148,255,163\" href=\"company_p17_a1017.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"215,171,247,186\" href=\"company_p18_a1018.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"214,203,247,218\" href=\"company_p19_a1019.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"225,225,258,240\" href=\"company_p20_a1020.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"124,105,157,120\" href=\"company_p21_a1021.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"145,168,178,183\" href=\"company_p22_a1022.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"179,204,212,217\" href=\"company_p24_a1024.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"180,251,213,266\" href=\"company_p25_a1025.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"146,221,180,236\" href=\"company_p26_a1026.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"113,132,146,148\" href=\"company_p27_a1027.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"189,150,222,164\" href=\"company_p28_a1028.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"190,224,223,239\" href=\"company_p29_a1029.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"57,165,90,180\" href=\"company_p30_a1030.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"158,134,191,149\" href=\"company_p31_a1031.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"166,101,217,116\" href=\"company_p33_a1033.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"225,242,258,257\" href=\"company_p34_a1034.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("								<area shape=\"rect\" coords=\"259,233,292,248\" href=\"company_p35_a1035.html\" target=\"_blank\"/>\r\n");
	XYBody.Append("							</map>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"maplisttitle\">热门地区:</div>\r\n");
	XYBody.Append("						<div class=\"maplist\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_CLS_GuangDong").ToString() + "\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_CLS_ZheJiang").ToString() + "\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_CLS_JiangSu").ToString() + "\r\n");
	XYBody.Append("								" +  XYECOMCreateHTML("XY_CLS_OtherCity").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"maplisttitle\">最新加入企业:</div>\r\n");
	XYBody.Append("						<div class=\"maplist\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("                                " +  XYECOMCreateHTML("XY_CompanyIndex_ZuiXinJoinQiYe").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer\" style=\"height:6px;\"></div>\r\n");
	XYBody.Append("			<div class=\"area1\">\r\n");
	XYBody.Append("				<div class=\"hd\">\r\n");
	XYBody.Append("					<div class=\"tit\">\r\n");
	XYBody.Append("						<span class=\"fright\"><a href=\"\" class=\"black\">更多&raquo;</a></span>\r\n");
	XYBody.Append("						<a href=\"\" class=\"h2_compy3\"><h2>按行业查找</h2></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div class=\"cnt\">\r\n");
	XYBody.Append("					<div class=\"chanye\">\r\n");
	XYBody.Append("						<div class=\"chanyetitle12\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li class=\"left\">\r\n");
	XYBody.Append("								供应商\r\n");
	XYBody.Append("								<li>\r\n");
	XYBody.Append("									<A href=\"sell.html\"><img height=\"8\" alt=\"更多\" src=\"http://www.glass.cn/glass/company/arrow.gif\" width=\"4\"\r\n");
	XYBody.Append("											border=\"0\"></A> <A href=\"companyca_a.html\">更多</A>								</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft_pic\"><img src=\"http://www.glass.cn/glass/company/changye_1.gif\"></div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("							" +  XYECOMCreateHTML("XY_CompanyIndex_QiYeTypeGongYingShang").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"chanye\">\r\n");
	XYBody.Append("						<div class=\"chanyetitle12\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li class=\"left\">\r\n");
	XYBody.Append("								采购商\r\n");
	XYBody.Append("								<li>\r\n");
	XYBody.Append("									<A href=\"sell.html\"><img height=\"8\" alt=\"更多\" src=\"http://www.glass.cn/glass/company/arrow.gif\" width=\"4\"\r\n");
	XYBody.Append("											border=\"0\"></A> <A href=\"companyca_b.html\">更多</A>								</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft_pic\"><img src=\"http://www.glass.cn/glass/company/changye_2.gif\"></div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("							    " +  XYECOMCreateHTML("XY_CompanyIndex_QiYeTypeCaiGouShang").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"chanye\">\r\n");
	XYBody.Append("						<div class=\"chanyetitle12\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li class=\"left\">\r\n");
	XYBody.Append("								零售商\r\n");
	XYBody.Append("								<li>\r\n");
	XYBody.Append("									<A href=\"sell.html\"><img height=\"8\" alt=\"更多\" src=\"http://www.glass.cn/glass/company/arrow.gif\" width=\"4\"\r\n");
	XYBody.Append("											border=\"0\"></A> <A href=\"companyca_c.html\">更多</A>								</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft_pic\"><img src=\"http://www.glass.cn/glass/company/changye_3.gif\"></div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("                                " +  XYECOMCreateHTML("XY_CompanyIndex_QiYeTypeLingShouShang").ToString() + "\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"chanye\">\r\n");
	XYBody.Append("						<div class=\"chanyetitle12\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("								<li class=\"left\">\r\n");
	XYBody.Append("								其它\r\n");
	XYBody.Append("								<li>\r\n");
	XYBody.Append("									<A href=\"sell.html\"><img height=\"8\" alt=\"更多\" src=\"http://www.glass.cn/glass/company/arrow.gif\" width=\"4\"\r\n");
	XYBody.Append("											border=\"0\"></A> <A href=\"companyca_c.html\">更多</A>								</li>\r\n");
	XYBody.Append("							</ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft_pic\"><img src=\"http://www.glass.cn/glass/company/changye_3.gif\"></div>\r\n");
	XYBody.Append("						<div class=\"chanyeleft\">\r\n");
	XYBody.Append("							<ul>\r\n");
	XYBody.Append("                                " +  XYECOMCreateHTML("XY_CompanyIndex_QiYeTypeOther").ToString() + "\r\n");
	XYBody.Append("						    </ul>\r\n");
	XYBody.Append("						</div>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("					<div class=\"clr\"></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div id=\"right\">\r\n");
	XYBody.Append("			<div id=\"gold_user\" style=\"margin-top:0;\">\r\n");
	XYBody.Append("				<div class=\"top\">\r\n");
	XYBody.Append("					<div class=\"tit\"><span class=\"fright\">更多></span><h2>金牌商家展示</h2></div>\r\n");
	XYBody.Append("					<div class=\"slogan\"><a href=\"\" class=\"red big\"><strong>马上入住金牌商家，商机无限>></strong></a></div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<div id=\"slidetexts\" class=\"mid\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("					    " +  XYECOMCreateHTML("XY_Index_JinPaiShangJiaZhanShi").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<script type=\"text/javascript\">\r\n");
	XYBody.Append("				<!--\r\n");
	XYBody.Append("					try{\r\n");
	XYBody.Append("					 slideLine('slidetexts', 3000, 5, 40);\r\n");
	XYBody.Append("					}catch(e) {}\r\n");
	XYBody.Append("				//-->\r\n");
	XYBody.Append("				</" + "script>\r\n");
	XYBody.Append("				<div class=\"btm spacer\"></div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"compy_cates\">\r\n");
	XYBody.Append("				<div class=\"tit\">公司分类：</div>\r\n");
	XYBody.Append("				<h5 class=\"name\">建筑外墙配套玻璃</h5>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<h5 class=\"name\">建筑外墙配套玻璃</h5>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<h5 class=\"name\">建筑外墙配套玻璃</h5>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("				<h5 class=\"name\">建筑外墙配套玻璃</h5>\r\n");
	XYBody.Append("				<div class=\"item\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">建筑玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">钢化玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">中空玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">夹层玻璃</a></li>\r\n");
	XYBody.Append("						<li><a href=\"\" target=\"_blank\">防弹玻璃</a></li>\r\n");
	XYBody.Append("						<div class=\"clr\"></div>\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div class=\"spacer\" style=\"height:7px;\"></div>\r\n");
	XYBody.Append("			<div class=\"MTitle_01\">\r\n");
	XYBody.Append("				<h2 id=\"y_tab1\" class=\"\" onmouseover=\"xy_selectBox(2,1,'y','selected');\"><a target=\"_blank\" href=\"#\">名优企业</a></h2>\r\n");
	XYBody.Append("			    <h2 id=\"y_tab2\" class=\"selected\" onmouseout=\"xy_selectBox(2,2,'y','selected');\"><a target=\"_blank\" href=\"#\">最新企业</a></h2>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"y_box1\" class=\"Mblk_01\" style=\"display:none;\">\r\n");
	XYBody.Append("				<div class=\"rank_compy\">\r\n");
	XYBody.Append("					<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_MingYouQiYe").ToString() + "\r\n");
	XYBody.Append("					</ul>\r\n");
	XYBody.Append("					<div class=\"rank_pic\">\r\n");
	XYBody.Append("						<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_11.gif\" width=\"238\" height=\"50\" alt=\"\" /></a>\r\n");
	XYBody.Append("					</div>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("			<div id=\"y_box2\" class=\"Mblk_01\" style=\"display:block;\">\r\n");
	XYBody.Append("			<div class=\"rank_compy\">\r\n");
	XYBody.Append("				<ul>\r\n");
	XYBody.Append("						" +  XYECOMCreateHTML("XY_Index_ZuiXinQiYe").ToString() + "\r\n");
	XYBody.Append("				</ul>\r\n");
	XYBody.Append("				<div class=\"rank_pic\">\r\n");
	XYBody.Append("					<a href=\"\"><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/temp_pic_11.gif\" width=\"238\" height=\"50\" alt=\"\" /></a>\r\n");
	XYBody.Append("				</div>\r\n");
	XYBody.Append("			</div>\r\n");
	XYBody.Append("		    </div>\r\n");
	XYBody.Append("        </div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"clr\"></div>\r\n");
	XYBody.Append("	</div>\r\n");

	XYBody.Append("	<div id=\"footer\">\r\n");
	XYBody.Append("		<a href=\"\">集团首页</a> | <a href=\"/about/index.htm\" target=\"_blank\">关于我们</a> | <a href=\"\">免责声明</a> | <a href=\"\">媒体报道</a> | <a href=\"\">诚聘英才</a> | <a href=\"\">代理专区</a> | <a href=\"\">广告专区</a> | <a href=\"\">友情链接</a> | <a href=\"\">联系我们</a> | <a href=\"\">网站地图</a>\r\n");
	XYBody.Append("	</div>\r\n");
	XYBody.Append("	<div id=\"copyright\">\r\n");
	XYBody.Append("		<div id=\"copy_info\">\r\n");
	XYBody.Append("			<ul>\r\n");
	XYBody.Append("				<li>Copyright &copy; 2005-2009  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href=\"#\" target=\"_blank\">京ICP备05003331号</a></li>\r\n");
	XYBody.Append("				<li><img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_phone.gif\" align=\"absmiddle\">电话：86-010-62669815 传真：86-010-86818791  <img src=\"");	XYBody.Append(config.WebURL);	XYBody.Append("templates/");	XYBody.Append(config.TemplatePath);	XYBody.Append("/images/ico_email.gif\" />E-Mail：<a href=\"#\">info@xyecom.com </a></li>\r\n");
	XYBody.Append("				<li>版权所有　纵横易商软件 - 致力于中小企业电子商务应用技术服务　未经授权请勿转载</li>\r\n");
	XYBody.Append("			</ul>			\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("		<div class=\"copyright_i\">\r\n");
	XYBody.Append("		 <div class=\"com copyright_i1\"><p class=\"p\"><a href=\"#\" target=\"_blank\">深圳网络警察报警平台</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i2\"><p class=\"p\">公共信息安全网络监察</p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i3\"><p class=\"p\"><a href=\"#\" target=\"_blank\">经营性网站备案信息</a></p></div>\r\n");
	XYBody.Append("		 <div class=\"com copyright_i4\"><p class=\"p\"><a href=\"#\" target=\"_blank\">不良信息举报中心</a></p></div>\r\n");
	XYBody.Append("		</div>\r\n");
	XYBody.Append("	 </div>\r\n");


	XYBody.Append("</div>\r\n");
	XYBody.Append("</body>\r\n");
	XYBody.Append("</html>\r\n");

	XYBody.Append(IsCopyright());
	Response.Write(XYBody.ToString());
}
</script>
